import { CraftingItem } from './types';

export const itemsData: CraftingItem[] = [
  {
    id: 'copper_sword',
    name: 'Épée en cuivre',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Copper_Sword.png',
    stats: { damage: 9, speed: 21, tooltip: 'Une épée de base.' },
    ingredients: [{ name: 'Barre de cuivre', quantity: 7 }],
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_sword',
    name: 'Épée en fer',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Iron_Sword.png',
    stats: { damage: 13, speed: 20, tooltip: 'Une épée en fer solide.' },
    ingredients: [{ name: 'Barre de fer', quantity: 8 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'gold_sword',
    name: 'Épée en or',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Gold_Sword.png',
    stats: { damage: 15, speed: 18, tooltip: 'Plus tranchante que le fer.' },
    ingredients: [{ name: "Barre d'or", quantity: 8 }],
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'platinum_sword',
    name: 'Épée en platine',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Platinum_Sword.png',
    stats: { damage: 16, speed: 17, tooltip: 'Le meilleur des métaux de base.' },
    ingredients: [{ name: 'Barre de platine', quantity: 8 }],
    tier: 'Platine',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'light_bane',
    name: 'Fléau des ténèbres',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Light%27s_Bane.png',
    stats: { damage: 17, speed: 19, tooltip: "L'arme des ténèbres." },
    ingredients: [{ name: "Barre d'écorce démoniaque", quantity: 10 }],
    tier: 'Crimson/Corruption',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_armor_helmet',
    name: 'Casque en fer',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Iron_Helmet.png',
    stats: { defense: 3, tooltip: 'Partie de l\'armure en fer.' },
    ingredients: [{ name: 'Barre de fer', quantity: 5 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_armor_chest',
    name: 'Plastron en fer',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Iron_Chainmail.png',
    stats: { defense: 4, tooltip: 'Protège le torse.' },
    ingredients: [{ name: 'Barre de fer', quantity: 8 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_armor_greaves',
    name: 'Jambières en fer',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Iron_Greaves.png',
    stats: { defense: 3, tooltip: 'Protège les jambes.' },
    ingredients: [{ name: 'Barre de fer', quantity: 6 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'copper_pickaxe',
    name: 'Pioche en cuivre',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Copper_Pickaxe.png',
    stats: { pickaxePower: 35, damage: 4, tooltip: 'Permet de miner les blocs de base.' },
    ingredients: [
      { name: 'Barre de cuivre', quantity: 6 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Cuivre',
    craftedAt: 'Établi',
  },
  {
    id: 'iron_pickaxe',
    name: 'Pioche en fer',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Iron_Pickaxe.png',
    stats: { pickaxePower: 55, damage: 6, tooltip: 'Mine plus efficacement.' },
    ingredients: [
      { name: 'Barre de fer', quantity: 8 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'gold_pickaxe',
    name: 'Pioche en or',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Gold_Pickaxe.png',
    stats: { pickaxePower: 65, damage: 7, tooltip: 'Encore plus efficace.' },
    ingredients: [
      { name: "Barre d'or", quantity: 8 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Or',
    craftedAt: 'Établi',
  },
  {
    id: 'workbench',
    name: 'Établi',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Work_Bench.png',
    stats: { tooltip: 'Station de craft essentielle pour débuter.' },
    ingredients: [{ name: 'Bois', quantity: 10 }],
    tier: 'Début',
    craftedAt: 'Inventaire',
  },
  {
    id: 'furnace',
    name: 'Fourneau',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Furnace.png',
    stats: { tooltip: 'Permet de fondre les minerais en barres.' },
    ingredients: [
      { name: 'Pierre', quantity: 20 },
      { name: 'Bois', quantity: 4 },
      { name: 'Torche', quantity: 3 },
    ],
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'anvil',
    name: 'Enclume de fer',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Iron_Anvil.png',
    stats: { tooltip: 'Permet de forger des armes et armures.' },
    ingredients: [{ name: 'Barre de fer', quantity: 5 }],
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'hellforge',
    name: 'Enfernoir',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/fr/Fichier:Hellforge.png',
    stats: { tooltip: "Fusionne le minerai d'enfer." },
    ingredients: [{ name: 'Fourneau', quantity: 1 }],
    tier: 'Enfer',
    craftedAt: 'Établi',
  },
];