import { CraftingItem } from './types';

// ============================================
// TERRARIA CRAFT HELPER
// 323 objets — Base de données complète
// Icônes originales du Terraria Wiki / Drive
// ============================================

const DRIVE = 'https://drive.google.com/uc?export=view&id=';
const WIKI = 'https://terraria.wiki.gg/images/';

export const itemsData: CraftingItem[] = [
  {
    id: 'adamantite_bar',
    name: 'Lingot d\'adamantite',
    category: 'Ressource',
    imageUrl: `${DRIVE}15V5Y5vSxbSsIZsvG_OJXoxg3hcTE3sXk`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Forge d\'adamantite',
  },
  {
    id: 'adamantite_chest',
    name: 'Plastron en adamantite',
    category: 'Armure',
    imageUrl: `${WIKI}Adamantite_Chest.png`,
    stats: { defense: 12 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'adamantite_forge',
    name: 'Forge d\'adamantite',
    category: 'Station de craft',
    imageUrl: `${WIKI}Adamantite_Forge.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enfernoir',
  },
  {
    id: 'adamantite_greaves',
    name: 'Jambières en adamantite',
    category: 'Armure',
    imageUrl: `${WIKI}Adamantite_Greaves.png`,
    stats: { defense: 9 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'adamantite_helmet',
    name: 'Casque en adamantite',
    category: 'Armure',
    imageUrl: `${WIKI}Adamantite_Helmet.png`,
    stats: { defense: 15 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'adamantite_ore',
    name: 'Minerai d\'adamantite',
    category: 'Ressource',
    imageUrl: `${DRIVE}1Rvj3KUD-7XA_iySMaFdj7dl6JlMFO-SN`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: undefined,
  },
  {
    id: 'adamantite_pickaxe',
    name: 'Pioche en adamantite',
    category: 'Outil',
    imageUrl: `${DRIVE}13xZjEWX40ChQ8Q83HH7kIb6XodM6NNZL`,
    stats: { damage: 11, pickaxePower: 180 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'aglet',
    name: 'Embout',
    category: 'Accessoire',
    imageUrl: `${WIKI}Aglet.png`,
    stats: { tooltip: 'Vitesse augmentée' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'alchemy_table',
    name: 'Table d\'alchimie',
    category: 'Station de craft',
    imageUrl: `${DRIVE}1onGxsNjd0YN1AYVVKh8LmlCjv8x_vz3v`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'amethyst_staff',
    name: 'Bâton d\'améthyste',
    category: 'Arme',
    imageUrl: `${WIKI}Amethyst_Staff.png`,
    stats: { damage: 14 },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'angel_wings',
    name: 'Ailes d\'ange',
    category: 'Accessoire',
    imageUrl: `${WIKI}Angel_Wings.png`,
    stats: { tooltip: 'Vol' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'ankh_shield',
    name: 'Bouclier Ânkh',
    category: 'Accessoire',
    imageUrl: `${WIKI}Ankh_Shield.png`,
    stats: { tooltip: 'Immunité totale' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'anklet_of_wind',
    name: 'Bracelet du vent',
    category: 'Accessoire',
    imageUrl: `${WIKI}Anklet_Of_Wind.png`,
    stats: { tooltip: 'Vitesse augmentée' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'anvil',
    name: 'Enclume de fer',
    category: 'Station de craft',
    imageUrl: `${WIKI}Iron_Anvil.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'aqua_scepter',
    name: 'Sceptre d\'aqua',
    category: 'Arme',
    imageUrl: `${WIKI}Aqua_Scepter.png`,
    stats: { damage: 14 },
    ingredients: undefined,
    tier: 'Donjon',
    craftedAt: 'Butin',
  },
  {
    id: 'archery',
    name: 'Potion de tir',
    category: 'Potion',
    imageUrl: `${WIKI}Archery.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'avenger_emblem',
    name: 'Emblème du vengeur',
    category: 'Accessoire',
    imageUrl: `${WIKI}Avenger_Emblem.png`,
    stats: { tooltip: '+12% dégâts' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'bat_wings',
    name: 'Ailes de chauve-souris',
    category: 'Accessoire',
    imageUrl: `${WIKI}Bat_Wings.png`,
    stats: { tooltip: 'Vol' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'battle',
    name: 'Potion de combat',
    category: 'Potion',
    imageUrl: `${WIKI}Battle.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'bee_wings',
    name: 'Ailes d\'abeille',
    category: 'Accessoire',
    imageUrl: `${WIKI}Bee_Wings.png`,
    stats: { tooltip: 'Vol' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'beetle_chest',
    name: 'Plastron en scarabée',
    category: 'Armure',
    imageUrl: `${WIKI}Beetle_Chest.png`,
    stats: { defense: 19 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'beetle_greaves',
    name: 'Jambières en scarabée',
    category: 'Armure',
    imageUrl: `${WIKI}Beetle_Greaves.png`,
    stats: { defense: 15 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'beetle_helmet',
    name: 'Casque en scarabée',
    category: 'Armure',
    imageUrl: `${WIKI}Beetle_Helmet.png`,
    stats: { defense: 23 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'blade_of_grass',
    name: 'Lame d\'herbe',
    category: 'Arme',
    imageUrl: `${WIKI}Blade_of_Grass.png`,
    stats: { damage: 28, speed: 25 },
    ingredients: undefined,
    tier: 'Jungle',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'blizzard_in_a_bottle',
    name: 'Tempête en bouteille',
    category: 'Accessoire',
    imageUrl: `${WIKI}Blizzard_In_A_Bottle.png`,
    stats: { tooltip: 'Double saut' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'blizzard_staff',
    name: 'Bâton de blizzard',
    category: 'Arme',
    imageUrl: `${WIKI}Blizzard_Staff.png`,
    stats: { damage: 48 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'blood_butcherer',
    name: 'Éventreur sanguinaire',
    category: 'Arme',
    imageUrl: `${WIKI}Blood_Butcherer.png`,
    stats: { damage: 22, speed: 19 },
    ingredients: undefined,
    tier: 'Crimson',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'blood_lust_cluster',
    name: 'Grappe de sang',
    category: 'Outil',
    imageUrl: `${DRIVE}10XW4VeEuchR3j5wiyPsy9xIkcbwrp5Wf`,
    stats: { damage: 15 },
    ingredients: undefined,
    tier: 'Crimson',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'bookcase',
    name: 'Bibliothèque',
    category: 'Station de craft',
    imageUrl: `${WIKI}Bookcase.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Scierie',
  },
  {
    id: 'bottle',
    name: 'Bouteille',
    category: 'Station de craft',
    imageUrl: `${DRIVE}114HqShKoUaJb1YlfobBtLhO2z9yOstrW`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'builder',
    name: 'Potion de construction',
    category: 'Potion',
    imageUrl: `${WIKI}Builder.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'bundle_of_balloons',
    name: 'Pack de ballons',
    category: 'Accessoire',
    imageUrl: `${WIKI}Bundle_Of_Balloons.png`,
    stats: { tooltip: 'Multi-sauts + hauteur' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'butterfly_wings',
    name: 'Ailes de papillon',
    category: 'Accessoire',
    imageUrl: `${WIKI}Butterfly_Wings.png`,
    stats: { tooltip: 'Vol' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'cactus_sword',
    name: 'Épée en cactus',
    category: 'Arme',
    imageUrl: `${WIKI}Cactus_Sword.png`,
    stats: { damage: 10, speed: 20 },
    ingredients: undefined,
    tier: 'Cactus',
    craftedAt: 'Établi',
  },
  {
    id: 'calming',
    name: 'Potion d\'apaisement',
    category: 'Potion',
    imageUrl: `${WIKI}Calming.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'celebration_mk2',
    name: 'Célébration MK2',
    category: 'Arme',
    imageUrl: `${WIKI}Celebration_Mk2.png`,
    stats: { damage: 35 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Butin',
  },
  {
    id: 'celestial_emblem',
    name: 'Emblème céleste',
    category: 'Accessoire',
    imageUrl: `${WIKI}Celestial_Emblem.png`,
    stats: { tooltip: '+15% magie + mana' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'cell_phone',
    name: 'Téléphone portable',
    category: 'Accessoire',
    imageUrl: `${WIKI}Cell_Phone.png`,
    stats: { tooltip: 'Infos complètes' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'chlorophyte_bar',
    name: 'Lingot de chlorophyte',
    category: 'Ressource',
    imageUrl: `${DRIVE}1Ncb1qTnS9YCl0O-F3I2T5uRy4EvjAit2`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Forge d\'adamantite',
  },
  {
    id: 'chlorophyte_chest',
    name: 'Plastron en chlorophyte',
    category: 'Armure',
    imageUrl: `${WIKI}Chlorophyte_Chest.png`,
    stats: { defense: 16 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'chlorophyte_greaves',
    name: 'Jambières en chlorophyte',
    category: 'Armure',
    imageUrl: `${WIKI}Chlorophyte_Greaves.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'chlorophyte_helmet',
    name: 'Casque en chlorophyte',
    category: 'Armure',
    imageUrl: `${WIKI}Chlorophyte_Helmet.png`,
    stats: { defense: 12 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'chlorophyte_ore',
    name: 'Minerai de chlorophyte',
    category: 'Ressource',
    imageUrl: `${DRIVE}1K-2wXyqpbHU7dJASXqVxgCstJLsQCzUQ`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: undefined,
  },
  {
    id: 'chlorophyte_pickaxe',
    name: 'Pioche en chlorophyte',
    category: 'Outil',
    imageUrl: `${DRIVE}1bq1cfFJfiMvy3A77QUl9m_8183cTSLva`,
    stats: { damage: 10, pickaxePower: 200 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'christmas_tree_sword',
    name: 'Épée sapin de Noël',
    category: 'Arme',
    imageUrl: `${WIKI}Christmas_Tree_Sword.png`,
    stats: { damage: 73, speed: 26 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'cloud_in_a_bottle',
    name: 'Nuage en bouteille',
    category: 'Accessoire',
    imageUrl: `${WIKI}Cloud_In_A_Bottle.png`,
    stats: { tooltip: 'Double saut' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'cobalt_bar',
    name: 'Lingot de cobalt',
    category: 'Ressource',
    imageUrl: `${DRIVE}1itHkfJEg3kIC7fwJyVIoojKOaBV9LkIr`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Fourneau',
  },
  {
    id: 'cobalt_chest',
    name: 'Plastron en cobalt',
    category: 'Armure',
    imageUrl: `${WIKI}Cobalt_Chest.png`,
    stats: { defense: 8 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'cobalt_greaves',
    name: 'Jambières en cobalt',
    category: 'Armure',
    imageUrl: `${WIKI}Cobalt_Greaves.png`,
    stats: { defense: 7 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'cobalt_helmet',
    name: 'Casque en cobalt',
    category: 'Armure',
    imageUrl: `${WIKI}Cobalt_Helmet.png`,
    stats: { defense: 11 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'cobalt_ore',
    name: 'Minerai de cobalt',
    category: 'Ressource',
    imageUrl: `${DRIVE}1qxYsPTRzTizm9zR1oD7C8cfkczljdc8N`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: undefined,
  },
  {
    id: 'cobalt_pickaxe',
    name: 'Pioche en cobalt',
    category: 'Outil',
    imageUrl: `${DRIVE}14Z97BjcUmslo4-4SCO7e6CvR9rdVA2v-`,
    stats: { damage: 8, pickaxePower: 110 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'copper_axe',
    name: 'Hache en cuivre',
    category: 'Outil',
    imageUrl: `${DRIVE}1xF7MzCchFJSUAdG6H80DyseSa7iCz926`,
    stats: { damage: 4 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Établi',
  },
  {
    id: 'copper_bar',
    name: 'Lingot de cuivre',
    category: 'Ressource',
    imageUrl: `${DRIVE}1H0QFwEqnqeJNl2VKDW7IIq71riA8WxeH`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Fourneau',
  },
  {
    id: 'copper_bow',
    name: 'Arc en cuivre',
    category: 'Arme',
    imageUrl: `${WIKI}Copper_Bow.png`,
    stats: { damage: 6 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Établi',
  },
  {
    id: 'copper_chest',
    name: 'Plastron en cuivre',
    category: 'Armure',
    imageUrl: `${WIKI}Copper_Chainmail.png`,
    stats: { defense: 3 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'copper_greaves',
    name: 'Jambières en cuivre',
    category: 'Armure',
    imageUrl: `${WIKI}Copper_Greaves.png`,
    stats: { defense: 2 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'copper_hammer',
    name: 'Marteau en cuivre',
    category: 'Outil',
    imageUrl: `${DRIVE}1Q6fOaefgU28Wt3sLoQ2dp9dWnEJ-C4Wy`,
    stats: { damage: 5 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Établi',
  },
  {
    id: 'copper_helmet',
    name: 'Casque en cuivre',
    category: 'Armure',
    imageUrl: `${WIKI}Copper_Helmet.png`,
    stats: { defense: 2 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'copper_ore',
    name: 'Minerai de cuivre',
    category: 'Ressource',
    imageUrl: `${DRIVE}133oZx7VUsyPVdanr8GyYt7WFXxDEtMPH`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: undefined,
  },
  {
    id: 'copper_pickaxe',
    name: 'Pioche en cuivre',
    category: 'Outil',
    imageUrl: `${DRIVE}1Ch8XZxffIn91Zpznz057dDifFroSOvRL`,
    stats: { damage: 4, pickaxePower: 35 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Établi',
  },
  {
    id: 'copper_sword',
    name: 'Épée en cuivre',
    category: 'Arme',
    imageUrl: `${WIKI}Copper_Broadsword.png`,
    stats: { damage: 9, speed: 21 },
    ingredients: undefined,
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'crate',
    name: 'Potion de caisse',
    category: 'Potion',
    imageUrl: `${WIKI}Crate.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'crimtane_bar',
    name: 'Lingot de crimtane',
    category: 'Ressource',
    imageUrl: `${DRIVE}1Bc8G__zs6tgj7fpf-LRcgK3typGGPjQE`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Crimson',
    craftedAt: 'Fourneau',
  },
  {
    id: 'crimtane_ore',
    name: 'Minerai de crimtane',
    category: 'Ressource',
    imageUrl: `${DRIVE}1sckC1nBMxBhPWrgnlI_tnQrMV1VS_5FL`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Crimson',
    craftedAt: undefined,
  },
  {
    id: 'crystal_ball',
    name: 'Boule de cristal',
    category: 'Station de craft',
    imageUrl: `${WIKI}Crystal_Ball.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'crystal_storm',
    name: 'Tempête de cristal',
    category: 'Arme',
    imageUrl: `${WIKI}Crystal_Storm.png`,
    stats: { damage: 39 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'cursed_flames',
    name: 'Flammes maudites',
    category: 'Arme',
    imageUrl: `${WIKI}Cursed_Flames.png`,
    stats: { damage: 44 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'deathbringer_pickaxe',
    name: 'Pioche de mort',
    category: 'Outil',
    imageUrl: `${DRIVE}1P7gCuAgn-TFUt8RNnTy6-UCwPJoOcoxR`,
    stats: { damage: 8, pickaxePower: 55 },
    ingredients: undefined,
    tier: 'Corruption',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'demon_bow',
    name: 'Arc démoniaque',
    category: 'Arme',
    imageUrl: `${WIKI}Demon_Bow.png`,
    stats: { damage: 14 },
    ingredients: undefined,
    tier: 'Corruption',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'demon_wings',
    name: 'Ailes démoniaques',
    category: 'Accessoire',
    imageUrl: `${WIKI}Demon_Wings.png`,
    stats: { tooltip: 'Vol' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'demonite_bar',
    name: 'Lingot de démonite',
    category: 'Ressource',
    imageUrl: `${DRIVE}1Ai31WNfJaMuKT8hSDgfU0E-Plc5rxnx0`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Corruption',
    craftedAt: 'Fourneau',
  },
  {
    id: 'demonite_ore',
    name: 'Minerai de démonite',
    category: 'Ressource',
    imageUrl: `${DRIVE}1ZuMJuz6-Mh3mEeGfOT3WrJcqSaILBuWc`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Corruption',
    craftedAt: undefined,
  },
  {
    id: 'destroyer_emblem',
    name: 'Emblème du destructeur',
    category: 'Accessoire',
    imageUrl: `${WIKI}Destroyer_Emblem.png`,
    stats: { tooltip: '+10% dégâts + critique' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'diamond_staff',
    name: 'Bâton de diamant',
    category: 'Arme',
    imageUrl: `${WIKI}Diamond_Staff.png`,
    stats: { damage: 32 },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'emerald_staff',
    name: 'Bâton d\'émeraude',
    category: 'Arme',
    imageUrl: `${WIKI}Emerald_Staff.png`,
    stats: { damage: 24 },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'empress_wings',
    name: 'Ailes de l\'impératrice',
    category: 'Accessoire',
    imageUrl: `${WIKI}Empress_Wings.png`,
    stats: { tooltip: 'Vol ultime + rainbow' },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Butin',
  },
  {
    id: 'enchanted_sword',
    name: 'Épée enchantée',
    category: 'Arme',
    imageUrl: `${WIKI}Enchanted_Sword.png`,
    stats: { damage: 23, speed: 21 },
    ingredients: undefined,
    tier: 'Spécial',
    craftedAt: 'Butin',
  },
  {
    id: 'endurance',
    name: 'Potion d\'endurance',
    category: 'Potion',
    imageUrl: `${WIKI}Endurance.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'excalibur',
    name: 'Excalibur',
    category: 'Arme',
    imageUrl: `${WIKI}Excalibur.png`,
    stats: { damage: 57, speed: 20 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'fairy_wings',
    name: 'Ailes de fée',
    category: 'Accessoire',
    imageUrl: `${WIKI}Fairy_Wings.png`,
    stats: { tooltip: 'Vol' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'featherfall',
    name: 'Potion de chute de plume',
    category: 'Potion',
    imageUrl: `${WIKI}Featherfall.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'fiery_greatsword',
    name: 'Épée de feu',
    category: 'Arme',
    imageUrl: `${WIKI}Fiery_Greatsword.png`,
    stats: { damage: 36, speed: 29 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'fire_gauntlet',
    name: 'Gantelet de feu',
    category: 'Accessoire',
    imageUrl: `${WIKI}Fire_Gauntlet.png`,
    stats: { tooltip: '+10% mêlée + feu' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'fishing',
    name: 'Potion de pêche',
    category: 'Potion',
    imageUrl: `${WIKI}Fishing.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'flame_wings',
    name: 'Ailes de flamme',
    category: 'Accessoire',
    imageUrl: `${WIKI}Flame_Wings.png`,
    stats: { tooltip: 'Vol tardif' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'fledgling_wings',
    name: 'Ailes de l\'oiselet',
    category: 'Accessoire',
    imageUrl: `${WIKI}Fledgling_Wings.png`,
    stats: { tooltip: 'Vol basique' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'flower_of_fire',
    name: 'Fleur de feu',
    category: 'Arme',
    imageUrl: `${WIKI}Flower_Of_Fire.png`,
    stats: { damage: 30 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'frost_wings',
    name: 'Ailes de givre',
    category: 'Accessoire',
    imageUrl: `${WIKI}Frost_Wings.png`,
    stats: { tooltip: 'Vol tardif' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'frostspark_boots',
    name: 'Bottes des flammes de givre',
    category: 'Accessoire',
    imageUrl: `${WIKI}Frostspark_Boots.png`,
    stats: { tooltip: 'Course + vol + glace' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'frozen_shield',
    name: 'Bouclier gelé',
    category: 'Accessoire',
    imageUrl: `${WIKI}Frozen_Shield.png`,
    stats: { tooltip: 'Protection + gel' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'furnace',
    name: 'Fourneau',
    category: 'Station de craft',
    imageUrl: `${WIKI}Furnace.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'gender_change',
    name: 'Potion de changement de genre',
    category: 'Potion',
    imageUrl: `${WIKI}Gender_Change.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'gold_axe',
    name: 'Hache en or',
    category: 'Outil',
    imageUrl: `${DRIVE}1bzMHcpTuErzxWMjfBNyvTB7pyDsbT_qz`,
    stats: { damage: 8 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Établi',
  },
  {
    id: 'gold_bar',
    name: 'Lingot d\'or',
    category: 'Ressource',
    imageUrl: `${DRIVE}1GpFwkuV8EAV158TbOeJB01NFq10Doqak`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Fourneau',
  },
  {
    id: 'gold_bow',
    name: 'Arc en or',
    category: 'Arme',
    imageUrl: `${WIKI}Gold_Bow.png`,
    stats: { damage: 10 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Établi',
  },
  {
    id: 'gold_chest',
    name: 'Plastron en or',
    category: 'Armure',
    imageUrl: `${WIKI}Gold_Chainmail.png`,
    stats: { defense: 5 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'gold_greaves',
    name: 'Jambières en or',
    category: 'Armure',
    imageUrl: `${WIKI}Gold_Greaves.png`,
    stats: { defense: 3 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'gold_hammer',
    name: 'Marteau en or',
    category: 'Outil',
    imageUrl: `${DRIVE}17K1KYfIbHxzrjYkOrqcqhTj_5wMIjAzm`,
    stats: { damage: 10 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Établi',
  },
  {
    id: 'gold_helmet',
    name: 'Casque en or',
    category: 'Armure',
    imageUrl: `${WIKI}Gold_Helmet.png`,
    stats: { defense: 4 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'gold_ore',
    name: 'Minerai d\'or',
    category: 'Ressource',
    imageUrl: `${DRIVE}10zt3N222wkRaHusERM_M4YGRDT_h_gg6`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Or',
    craftedAt: undefined,
  },
  {
    id: 'gold_pickaxe',
    name: 'Pioche en or',
    category: 'Outil',
    imageUrl: `${DRIVE}1Xa0VkEmfouC_3Q90n4Onfga-eOLQCSjC`,
    stats: { damage: 7, pickaxePower: 65 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Établi',
  },
  {
    id: 'gold_sword',
    name: 'Épée en or',
    category: 'Arme',
    imageUrl: `${WIKI}Gold_Broadsword.png`,
    stats: { damage: 15, speed: 18 },
    ingredients: undefined,
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'golden_shower',
    name: 'Pluie dorée',
    category: 'Arme',
    imageUrl: `${WIKI}Golden_Shower.png`,
    stats: { damage: 40 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'greater_healing',
    name: 'Potion de soin supérieure',
    category: 'Potion',
    imageUrl: `${WIKI}Greater_Healing.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'greater_mana',
    name: 'Potion de mana supérieure',
    category: 'Potion',
    imageUrl: `${WIKI}Greater_Mana.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'hallowed_chest',
    name: 'Plastron sacré',
    category: 'Armure',
    imageUrl: `${WIKI}Hallowed_Chest.png`,
    stats: { defense: 13 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'hallowed_greaves',
    name: 'Jambières sacrées',
    category: 'Armure',
    imageUrl: `${WIKI}Hallowed_Greaves.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'hallowed_helmet',
    name: 'Casque sacré',
    category: 'Armure',
    imageUrl: `${WIKI}Hallowed_Helmet.png`,
    stats: { defense: 17 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'healing_potion',
    name: 'Potion de soin',
    category: 'Potion',
    imageUrl: `${WIKI}Healing_Potion.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'heat_ray',
    name: 'Rayon de chaleur',
    category: 'Arme',
    imageUrl: `${WIKI}Heat_Ray.png`,
    stats: { damage: 60 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'hellforge',
    name: 'Enfernoir',
    category: 'Station de craft',
    imageUrl: `${WIKI}Hellforge.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Établi',
  },
  {
    id: 'hellstone',
    name: 'Pierre infernale',
    category: 'Ressource',
    imageUrl: `${DRIVE}1hv7rSMSTkf4mDuHDQD7foSUhs3KUneBg`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: undefined,
  },
  {
    id: 'hellstone_bar',
    name: 'Lingot infernal',
    category: 'Ressource',
    imageUrl: `${DRIVE}1a9Ypv-b3zdEfefDLanIGaPU0awqJ5sTc`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enfernoir',
  },
  {
    id: 'hermes_boots',
    name: 'Bottes d\'Hermès',
    category: 'Accessoire',
    imageUrl: `${WIKI}Hermes_Boots.png`,
    stats: { tooltip: 'Course超 rapide' },
    ingredients: undefined,
    tier: 'Butin',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'hero_shield',
    name: 'Bouclier du héros',
    category: 'Accessoire',
    imageUrl: `${WIKI}Hero_Shield.png`,
    stats: { tooltip: 'Protection ultime' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'horsemans_blade',
    name: 'Épée du cavalier',
    category: 'Arme',
    imageUrl: `${WIKI}Horsemans_Blade.png`,
    stats: { damage: 80, speed: 18 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'hoverboard',
    name: 'Hoverboard',
    category: 'Accessoire',
    imageUrl: `${WIKI}Hoverboard.png`,
    stats: { tooltip: 'Vol + glisse' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'hunter',
    name: 'Potion de chasseur',
    category: 'Potion',
    imageUrl: `${WIKI}Hunter.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'ice_bow',
    name: 'Arc de glace',
    category: 'Arme',
    imageUrl: `${WIKI}Ice_Bow.png`,
    stats: { damage: 39 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'ice_skates',
    name: 'Patin à glace',
    category: 'Accessoire',
    imageUrl: `${WIKI}Ice_Skates.png`,
    stats: { tooltip: 'Glisse sur glace' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'imbuing_station',
    name: 'Station d\'infusion',
    category: 'Station de craft',
    imageUrl: `${WIKI}Imbuing_Station.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'inferno',
    name: 'Potion d\'enfer',
    category: 'Potion',
    imageUrl: `${WIKI}Inferno.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Bouteille',
  },
  {
    id: 'inferno_fork',
    name: 'Fourche d\'enfer',
    category: 'Arme',
    imageUrl: `${WIKI}Inferno_Fork.png`,
    stats: { damage: 45 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'influx_waver',
    name: 'Onde de choc',
    category: 'Arme',
    imageUrl: `${WIKI}Influx_Waver.png`,
    stats: { damage: 85, speed: 20 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'invisibility',
    name: 'Potion d\'invisibilité',
    category: 'Potion',
    imageUrl: `${WIKI}Invisibility.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'iron_axe',
    name: 'Hache en fer',
    category: 'Outil',
    imageUrl: `${DRIVE}1JKX59kW8LCewc2tgDcbetvhuwSmdH5Rj`,
    stats: { damage: 6 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'iron_bar',
    name: 'Lingot de fer',
    category: 'Ressource',
    imageUrl: `${DRIVE}1KRZ4Wb9tAqO_q54hmg7nWL7Q4F7-XcJl`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Fourneau',
  },
  {
    id: 'iron_bow',
    name: 'Arc en fer',
    category: 'Arme',
    imageUrl: `${WIKI}Iron_Bow.png`,
    stats: { damage: 8 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'iron_chest',
    name: 'Plastron en fer',
    category: 'Armure',
    imageUrl: `${WIKI}Iron_Chainmail.png`,
    stats: { defense: 4 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_greaves',
    name: 'Jambières en fer',
    category: 'Armure',
    imageUrl: `${WIKI}Iron_Greaves.png`,
    stats: { defense: 3 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_hammer',
    name: 'Marteau en fer',
    category: 'Outil',
    imageUrl: `${DRIVE}1OXrp-g0_ta_TnQ9aHhPWX0XzM_uhf-ZB`,
    stats: { damage: 8 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'iron_helmet',
    name: 'Casque en fer',
    category: 'Armure',
    imageUrl: `${WIKI}Iron_Helmet.png`,
    stats: { defense: 3 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_ore',
    name: 'Minerai de fer',
    category: 'Ressource',
    imageUrl: `${DRIVE}1G7ZU4rWaUn_ADW3-ZtoMskJN3dm9cW1b`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: undefined,
  },
  {
    id: 'iron_pickaxe',
    name: 'Pioche en fer',
    category: 'Outil',
    imageUrl: `${DRIVE}1hOpUwMmrReGvADDQGq0oQ5tztUZTZclX`,
    stats: { damage: 6, pickaxePower: 55 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'iron_sword',
    name: 'Épée en fer',
    category: 'Arme',
    imageUrl: `${WIKI}Iron_Broadsword.png`,
    stats: { damage: 13, speed: 20 },
    ingredients: undefined,
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'ironskin',
    name: 'Potion de peau de fer',
    category: 'Potion',
    imageUrl: `${WIKI}Ironskin.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'last_prism',
    name: 'Dernier prisme',
    category: 'Arme',
    imageUrl: `${WIKI}Last_Prism.png`,
    stats: { damage: 100 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Butin',
  },
  {
    id: 'lava_charm',
    name: 'Charme de lave',
    category: 'Accessoire',
    imageUrl: `${WIKI}Lava_Charm.png`,
    stats: { tooltip: 'Marche dans la lave' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'lava_waders',
    name: 'Cuissardes de lave',
    category: 'Accessoire',
    imageUrl: `${WIKI}Lava_Waders.png`,
    stats: { tooltip: 'Marche lave + eau' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'lead_axe',
    name: 'Hache en plomb',
    category: 'Outil',
    imageUrl: `${DRIVE}1yZrPxmhCXiFQydUdjWdhJ-CNiexK-bHp`,
    stats: { damage: 7 },
    ingredients: undefined,
    tier: 'Plomb',
    craftedAt: 'Établi',
  },
  {
    id: 'lead_bar',
    name: 'Lingot de plomb',
    category: 'Ressource',
    imageUrl: `${DRIVE}11l6hfxD0IUfACuvEqHZFRx8y2lCqSS7-`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Plomb',
    craftedAt: 'Fourneau',
  },
  {
    id: 'lead_hammer',
    name: 'Marteau en plomb',
    category: 'Outil',
    imageUrl: `${DRIVE}1gd8TIXChpgc9e1tYHMaxNKR_jT8Ez8nT`,
    stats: { damage: 9 },
    ingredients: undefined,
    tier: 'Plomb',
    craftedAt: 'Établi',
  },
  {
    id: 'lead_ore',
    name: 'Minerai de plomb',
    category: 'Ressource',
    imageUrl: `${DRIVE}14ZWuPicm4NJd6d9XOrjSmXUN-2wG47Fm`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Plomb',
    craftedAt: undefined,
  },
  {
    id: 'lead_pickaxe',
    name: 'Pioche en plomb',
    category: 'Outil',
    imageUrl: `${DRIVE}1iQNLidU0JSsYlAzNUKjZrChJvBdDX-uQ`,
    stats: { damage: 7, pickaxePower: 59 },
    ingredients: undefined,
    tier: 'Plomb',
    craftedAt: 'Établi',
  },
  {
    id: 'lead_sword',
    name: 'Épée en plomb',
    category: 'Arme',
    imageUrl: `${WIKI}Lead_Broadsword.png`,
    stats: { damage: 14, speed: 19 },
    ingredients: undefined,
    tier: 'Plomb',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'leaf_wings',
    name: 'Ailes de feuille',
    category: 'Accessoire',
    imageUrl: `${WIKI}Leaf_Wings.png`,
    stats: { tooltip: 'Vol' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'lesser_healing',
    name: 'Potion de soin mineure',
    category: 'Potion',
    imageUrl: `${WIKI}Lesser_Healing.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'lesser_mana',
    name: 'Potion de mana mineure',
    category: 'Potion',
    imageUrl: `${WIKI}Lesser_Mana.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'life_crystal',
    name: 'Cristal de vie',
    category: 'Accessoire',
    imageUrl: `${DRIVE}1WsezD9mwFv7thGFSdiJ3k59KBQI4b6nQ`,
    stats: { tooltip: 'Augmente la vie max de 20' },
    ingredients: undefined,
    tier: 'Minage',
    craftedAt: undefined,
  },
  {
    id: 'life_fruit',
    name: 'Fruit de vie',
    category: 'Accessoire',
    imageUrl: `${WIKI}Life_Fruit.png`,
    stats: { tooltip: 'Augmente la vie max de 5' },
    ingredients: undefined,
    tier: 'Minage',
    craftedAt: undefined,
  },
  {
    id: 'lifeforce',
    name: 'Potion de force vitale',
    category: 'Potion',
    imageUrl: `${WIKI}Lifeforce.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'light_bane',
    name: 'Fléau des ténèbres',
    category: 'Arme',
    imageUrl: `${WIKI}Light%27s_Bane.png`,
    stats: { damage: 17, speed: 19 },
    ingredients: undefined,
    tier: 'Corruption',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'lightning_boots',
    name: 'Bottes de l\'éclair',
    category: 'Accessoire',
    imageUrl: `${WIKI}Lightning_Boots.png`,
    stats: { tooltip: 'Course très rapide' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'loom',
    name: 'Métier à tisser',
    category: 'Station de craft',
    imageUrl: `${WIKI}Loom.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'luck_plus',
    name: 'Potion de chance',
    category: 'Potion',
    imageUrl: `${WIKI}Luck_Plus.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'lucky_horseshoe',
    name: 'Fer à cheval porte-bonheur',
    category: 'Accessoire',
    imageUrl: `${WIKI}Lucky_Horseshoe.png`,
    stats: { tooltip: 'Anti-chute' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'luminite',
    name: 'Luminite',
    category: 'Ressource',
    imageUrl: `${DRIVE}1FQYA-bjfWFrfTIRN3DNmtcXQFeJ8KpHC`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: undefined,
  },
  {
    id: 'luminite_bar',
    name: 'Lingot de luminite',
    category: 'Ressource',
    imageUrl: `${DRIVE}1HvUNsJ3OcyFjH9UhlD4XsXar1cJkccjr`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Forge d\'adamantite',
  },
  {
    id: 'lunar_flare',
    name: 'Éruption lunaire',
    category: 'Arme',
    imageUrl: `${WIKI}Lunar_Flare.png`,
    stats: { damage: 100 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'magic_mirror',
    name: 'Miroir magique',
    category: 'Accessoire',
    imageUrl: `${WIKI}Magic_Mirror.png`,
    stats: { tooltip: 'Retour au spawn' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'mana_crystal',
    name: 'Cristal de mana',
    category: 'Accessoire',
    imageUrl: `${DRIVE}1eFAD76v0rzXLPkMoPovCZayJFiwNhc7h`,
    stats: { tooltip: 'Augmente le mana max de 20' },
    ingredients: undefined,
    tier: 'Minage',
    craftedAt: undefined,
  },
  {
    id: 'mana_potion',
    name: 'Potion de mana',
    category: 'Potion',
    imageUrl: `${WIKI}Mana_Potion.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'marrow',
    name: 'Moelle',
    category: 'Arme',
    imageUrl: `${WIKI}Marrow.png`,
    stats: { damage: 40 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'mechanical_glove',
    name: 'Gant mécanique',
    category: 'Accessoire',
    imageUrl: `${WIKI}Mechanical_Glove.png`,
    stats: { tooltip: '+12% mêlée + vitesse' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'megashark',
    name: 'Méga-requin',
    category: 'Arme',
    imageUrl: `${WIKI}Megashark.png`,
    stats: { damage: 25 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'meowmere',
    name: 'Meowmere',
    category: 'Arme',
    imageUrl: `${WIKI}Meowmere.png`,
    stats: { damage: 200, speed: 15 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Butin',
  },
  {
    id: 'meteorite',
    name: 'Météorite',
    category: 'Ressource',
    imageUrl: `${DRIVE}16k2TZr0rg5GtQylpg2d-GiaHVcRc_8U8`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Météore',
    craftedAt: undefined,
  },
  {
    id: 'mining',
    name: 'Potion d\'extraction',
    category: 'Potion',
    imageUrl: `${WIKI}Mining.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'molten_chest',
    name: 'Plastron en fusion',
    category: 'Armure',
    imageUrl: `${WIKI}Molten_Breastplate.png`,
    stats: { defense: 9 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'molten_fury',
    name: 'Fureur en fusion',
    category: 'Arme',
    imageUrl: `${WIKI}Molten_Fury.png`,
    stats: { damage: 31 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'molten_greaves',
    name: 'Jambières en fusion',
    category: 'Armure',
    imageUrl: `${WIKI}Molten_Greaves.png`,
    stats: { defense: 7 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'molten_hamaxe',
    name: 'Hamache en fusion',
    category: 'Outil',
    imageUrl: `${DRIVE}1QJbE8-OeXV9MpbM6hz6BU7jjM4twWjhu`,
    stats: { damage: 20 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'molten_helmet',
    name: 'Casque en fusion',
    category: 'Armure',
    imageUrl: `${WIKI}Molten_Helmet.png`,
    stats: { defense: 8 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'molten_pickaxe',
    name: 'Pioche en fusion',
    category: 'Outil',
    imageUrl: `${DRIVE}1NtcYEjQRULyvxIf2xgG1KSGYqzkDKxdN`,
    stats: { damage: 12, pickaxePower: 100 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'muramasa',
    name: 'Muramasa',
    category: 'Arme',
    imageUrl: `${WIKI}Muramasa.png`,
    stats: { damage: 24, speed: 18 },
    ingredients: undefined,
    tier: 'Donjon',
    craftedAt: 'Butin',
  },
  {
    id: 'mythril_anvil',
    name: 'Enclume de mithril',
    category: 'Station de craft',
    imageUrl: `${WIKI}Mythril_Anvil.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'mythril_bar',
    name: 'Lingot de mithril',
    category: 'Ressource',
    imageUrl: `${DRIVE}1BPLV0ZpiCzSv7hkH6pVk20lPIUAfBcUA`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Fourneau',
  },
  {
    id: 'mythril_chest',
    name: 'Plastron en mithril',
    category: 'Armure',
    imageUrl: `${WIKI}Mythril_Chest.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'mythril_greaves',
    name: 'Jambières en mithril',
    category: 'Armure',
    imageUrl: `${WIKI}Mythril_Greaves.png`,
    stats: { defense: 8 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'mythril_helmet',
    name: 'Casque en mithril',
    category: 'Armure',
    imageUrl: `${WIKI}Mythril_Helmet.png`,
    stats: { defense: 13 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'mythril_ore',
    name: 'Minerai de mithril',
    category: 'Ressource',
    imageUrl: `${DRIVE}1WvPKtlAHFM_-jiumHXouPr5_khRESEPw`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: undefined,
  },
  {
    id: 'mythril_pickaxe',
    name: 'Pioche en mithril',
    category: 'Outil',
    imageUrl: `${DRIVE}1l0LAm-0ytuRFGW6gd5msmcMwzShnf0y2`,
    stats: { damage: 10, pickaxePower: 150 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'nebula_arcanum',
    name: 'Arcanum de nébuleuse',
    category: 'Arme',
    imageUrl: `${WIKI}Nebula_Arcanum.png`,
    stats: { damage: 70 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'nebula_chest',
    name: 'Plastron de nébuleuse',
    category: 'Armure',
    imageUrl: `${WIKI}Nebula_Chest.png`,
    stats: { defense: 13 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'nebula_greaves',
    name: 'Jambières de nébuleuse',
    category: 'Armure',
    imageUrl: `${WIKI}Nebula_Greaves.png`,
    stats: { defense: 11 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'nebula_wings',
    name: 'Ailes de nébuleuse',
    category: 'Accessoire',
    imageUrl: `${WIKI}Nebula_Wings.png`,
    stats: { tooltip: 'Vol ultime' },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'nebulа_helmet',
    name: 'Casque de nébuleuse',
    category: 'Armure',
    imageUrl: `${WIKI}Nebulа_Helmet.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'night_owl',
    name: 'Potion de vision nocturne',
    category: 'Potion',
    imageUrl: `${WIKI}Night_Owl.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'nightmare_pickaxe',
    name: 'Pioche de cauchemar',
    category: 'Outil',
    imageUrl: `${DRIVE}1S9BEY29MBtowZL-ANeKgaKYZn9aRX178`,
    stats: { damage: 9, pickaxePower: 55 },
    ingredients: undefined,
    tier: 'Crimson',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'nights_edge',
    name: 'Épée des ténèbres',
    category: 'Arme',
    imageUrl: `${WIKI}Nights_Edge.png`,
    stats: { damage: 42, speed: 19 },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'obsidian_shield',
    name: 'Bouclier d\'obsidienne',
    category: 'Accessoire',
    imageUrl: `${WIKI}Obsidian_Shield.png`,
    stats: { tooltip: 'Anti-recul + lave' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'obsidian_skin',
    name: 'Potion de peau d\'obsidienne',
    category: 'Potion',
    imageUrl: `${WIKI}Obsidian_Skin.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'obsidian_skull',
    name: 'Crâne d\'obsidienne',
    category: 'Accessoire',
    imageUrl: `${WIKI}Obsidian_Skull.png`,
    stats: { tooltip: 'Immunité lave' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'orichalcum_bar',
    name: 'Lingot d\'orichalque',
    category: 'Ressource',
    imageUrl: `${DRIVE}1P0KKZ4QPDJ0Sbt5wAdE1QdpgSRx_IH9G`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Fourneau',
  },
  {
    id: 'orichalcum_ore',
    name: 'Minerai d\'orichalque',
    category: 'Ressource',
    imageUrl: `${DRIVE}1hlbXAwFwqI_pYqu0EwrAFp_C9wLlvqVF`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: undefined,
  },
  {
    id: 'orichalcum_pickaxe',
    name: 'Pioche en orichalque',
    category: 'Outil',
    imageUrl: `${DRIVE}1g2P928Wjiey0EMfEcVr1r2pxad_TFbYR`,
    stats: { damage: 10, pickaxePower: 165 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'paladins_shield',
    name: 'Bouclier du paladin',
    category: 'Accessoire',
    imageUrl: `${WIKI}Paladins_Shield.png`,
    stats: { tooltip: 'Protège les alliés' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'palladium_bar',
    name: 'Lingot de palladium',
    category: 'Ressource',
    imageUrl: `${DRIVE}1fdThBvauWIQGqF7kEMNQo02Q7csdwLll`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Fourneau',
  },
  {
    id: 'palladium_ore',
    name: 'Minerai de palladium',
    category: 'Ressource',
    imageUrl: `${DRIVE}1RWO808XxM5zWenVe5dvjApZvtTKncTI4`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: undefined,
  },
  {
    id: 'palladium_pickaxe',
    name: 'Pioche en palladium',
    category: 'Outil',
    imageUrl: `${DRIVE}1Y2q2UUy5q1Ybm9caVpz6yS__858vgMjH`,
    stats: { damage: 9, pickaxePower: 130 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'phantasm',
    name: 'Fantasme',
    category: 'Arme',
    imageUrl: `${WIKI}Phantasm.png`,
    stats: { damage: 50 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'phoenix_blaster',
    name: 'Pétardeur phénix',
    category: 'Arme',
    imageUrl: `${WIKI}Phoenix_Blaster.png`,
    stats: { damage: 24 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'picksaw',
    name: 'Picksaw',
    category: 'Outil',
    imageUrl: `${DRIVE}17kZ7vmHjfPGisgWLfwZWGzLBxQAo0Hat`,
    stats: { damage: 20, pickaxePower: 210 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'platinum_axe',
    name: 'Hache en platine',
    category: 'Outil',
    imageUrl: `${DRIVE}1aMCoyLU0oy-4Uq81RMJEWf4YygB3QHJ_`,
    stats: { damage: 9 },
    ingredients: undefined,
    tier: 'Platine',
    craftedAt: 'Établi',
  },
  {
    id: 'platinum_bar',
    name: 'Lingot de platine',
    category: 'Ressource',
    imageUrl: `${DRIVE}1t8DLoL57H07ipRN2R2VPXIWmN-IqcrKx`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Platine',
    craftedAt: 'Fourneau',
  },
  {
    id: 'platinum_hammer',
    name: 'Marteau en platine',
    category: 'Outil',
    imageUrl: `${DRIVE}1-mw6fE8z8_HPyvGbijfF8Omk28lpzZQ0`,
    stats: { damage: 11 },
    ingredients: undefined,
    tier: 'Platine',
    craftedAt: 'Établi',
  },
  {
    id: 'platinum_ore',
    name: 'Minerai de platine',
    category: 'Ressource',
    imageUrl: `${DRIVE}1Gttf3MArW9U_zZFGVY-OnX53gFtB_G9Y`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Platine',
    craftedAt: undefined,
  },
  {
    id: 'platinum_pickaxe',
    name: 'Pioche en platine',
    category: 'Outil',
    imageUrl: `${DRIVE}1f3pzK2ciGANQaKCaAu6BPw-5Lp3IF_Zh`,
    stats: { damage: 9, pickaxePower: 70 },
    ingredients: undefined,
    tier: 'Platine',
    craftedAt: 'Établi',
  },
  {
    id: 'platinum_sword',
    name: 'Épée en platine',
    category: 'Arme',
    imageUrl: `${WIKI}Platinum_Broadsword.png`,
    stats: { damage: 16, speed: 17 },
    ingredients: undefined,
    tier: 'Platine',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'pwnhammer',
    name: 'Pwnhammer',
    category: 'Outil',
    imageUrl: `${DRIVE}13zn3h2Wp_3jdMMHEWgJtOyEs1DOZ_cBk`,
    stats: { damage: 19 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'rage',
    name: 'Potion de rage',
    category: 'Potion',
    imageUrl: `${WIKI}Rage.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Crimson',
    craftedAt: 'Bouteille',
  },
  {
    id: 'rainbow_rod',
    name: 'Baguette arc-en-ciel',
    category: 'Arme',
    imageUrl: `${WIKI}Rainbow_Rod.png`,
    stats: { damage: 44 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'ranger_emblem',
    name: 'Emblème du ranger',
    category: 'Accessoire',
    imageUrl: `${WIKI}Ranger_Emblem.png`,
    stats: { tooltip: '+15% dégâts distance' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'razorblade_of_the_moon',
    name: 'Lame de rasoir lunaire',
    category: 'Arme',
    imageUrl: `${WIKI}Razorblade_Of_The_Moon.png`,
    stats: { damage: 50 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Butin',
  },
  {
    id: 'razorblade_typhoon',
    name: 'Typhon en lame de rasoir',
    category: 'Arme',
    imageUrl: `${WIKI}Razorblade_Typhoon.png`,
    stats: { damage: 60 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'regeneration',
    name: 'Potion de régénération',
    category: 'Potion',
    imageUrl: `${WIKI}Regeneration.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'ruby_staff',
    name: 'Bâton de rubis',
    category: 'Arme',
    imageUrl: `${WIKI}Ruby_Staff.png`,
    stats: { damage: 28 },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'sandstorm_in_a_bottle',
    name: 'Tempête de sable en bouteille',
    category: 'Accessoire',
    imageUrl: `${WIKI}Sandstorm_In_A_Bottle.png`,
    stats: { tooltip: 'Double saut' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'sapphire_staff',
    name: 'Bâton de saphir',
    category: 'Arme',
    imageUrl: `${WIKI}Sapphire_Staff.png`,
    stats: { damage: 20 },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'sawmill',
    name: 'Scierie',
    category: 'Station de craft',
    imageUrl: `${WIKI}Sawmill.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'sdm',
    name: 'S.D.M.G.',
    category: 'Arme',
    imageUrl: `${WIKI}Sdm.png`,
    stats: { damage: 85 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Butin',
  },
  {
    id: 'seedler',
    name: 'Seedler',
    category: 'Arme',
    imageUrl: `${WIKI}Seedler.png`,
    stats: { damage: 60, speed: 25 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'shadow_chest',
    name: 'Plastron de l\'ombre',
    category: 'Armure',
    imageUrl: `${WIKI}Shadow_Scale_Mail.png`,
    stats: { defense: 7 },
    ingredients: undefined,
    tier: 'Ombre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'shadow_greaves',
    name: 'Jambières de l\'ombre',
    category: 'Armure',
    imageUrl: `${WIKI}Shadow_Greaves.png`,
    stats: { defense: 5 },
    ingredients: undefined,
    tier: 'Ombre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'shadow_helmet',
    name: 'Casque de l\'ombre',
    category: 'Armure',
    imageUrl: `${WIKI}Shadow_Helmet.png`,
    stats: { defense: 6 },
    ingredients: undefined,
    tier: 'Ombre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'sharanga',
    name: 'Sharanga',
    category: 'Arme',
    imageUrl: `${WIKI}Sharanga.png`,
    stats: { damage: 36 },
    ingredients: undefined,
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'shine',
    name: 'Potion de lumière',
    category: 'Potion',
    imageUrl: `${WIKI}Shine.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'shiny_red_balloon',
    name: 'Ballon rouge brillant',
    category: 'Accessoire',
    imageUrl: `${WIKI}Shiny_Red_Balloon.png`,
    stats: { tooltip: '+50% saut' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'shotgun',
    name: 'Fusil à pompe',
    category: 'Arme',
    imageUrl: `${WIKI}Shotgun.png`,
    stats: { damage: 18 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Achat',
  },
  {
    id: 'shroomite_digging_claw',
    name: 'Griffe champignonite',
    category: 'Outil',
    imageUrl: `${DRIVE}19K71LxR2-B04kVt7P495xuRce3v2HEbC`,
    stats: { damage: 12, pickaxePower: 200 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Autel',
  },
  {
    id: 'silver_axe',
    name: 'Hache en argent',
    category: 'Outil',
    imageUrl: `${DRIVE}14Oy_LI81s5WVnuu29UgS1nFP1ovECG-a`,
    stats: { damage: 8 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Établi',
  },
  {
    id: 'silver_bar',
    name: 'Lingot d\'argent',
    category: 'Ressource',
    imageUrl: `${DRIVE}1QmuaEYybNGsOD1IDWQzPdsEb-8HsNuGm`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Fourneau',
  },
  {
    id: 'silver_bow',
    name: 'Arc en argent',
    category: 'Arme',
    imageUrl: `${WIKI}Silver_Bow.png`,
    stats: { damage: 9 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Établi',
  },
  {
    id: 'silver_chest',
    name: 'Plastron en argent',
    category: 'Armure',
    imageUrl: `${WIKI}Silver_Chainmail.png`,
    stats: { defense: 4 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'silver_greaves',
    name: 'Jambières en argent',
    category: 'Armure',
    imageUrl: `${WIKI}Silver_Greaves.png`,
    stats: { defense: 3 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'silver_hammer',
    name: 'Marteau en argent',
    category: 'Outil',
    imageUrl: `${DRIVE}17eT51WDf7IoNkjz8lQmNsELIF79RMxop`,
    stats: { damage: 9 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Établi',
  },
  {
    id: 'silver_helmet',
    name: 'Casque en argent',
    category: 'Armure',
    imageUrl: `${WIKI}Silver_Helmet.png`,
    stats: { defense: 3 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'silver_ore',
    name: 'Minerai d\'argent',
    category: 'Ressource',
    imageUrl: `${DRIVE}1X1_yRkFqGeJGrlfKTHYfiqxE0W65M-Qu`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: undefined,
  },
  {
    id: 'silver_pickaxe',
    name: 'Pioche en argent',
    category: 'Outil',
    imageUrl: `${DRIVE}1pTWFL0i3qC2twcwgmNaAfhev_eKASdop`,
    stats: { damage: 8, pickaxePower: 65 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Établi',
  },
  {
    id: 'silver_sword',
    name: 'Épée en argent',
    category: 'Arme',
    imageUrl: `${WIKI}Silver_Broadsword.png`,
    stats: { damage: 14, speed: 19 },
    ingredients: undefined,
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'sniper_rifle',
    name: 'Fusil de sniper',
    category: 'Arme',
    imageUrl: `${WIKI}Sniper_Rifle.png`,
    stats: { damage: 185 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'solar_flare_chest',
    name: 'Plastron d\'éruption solaire',
    category: 'Armure',
    imageUrl: `${WIKI}Solar_Flare_Chest.png`,
    stats: { defense: 34 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'solar_flare_greaves',
    name: 'Jambières d\'éruption solaire',
    category: 'Armure',
    imageUrl: `${WIKI}Solar_Flare_Greaves.png`,
    stats: { defense: 22 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'solar_flare_helmet',
    name: 'Casque d\'éruption solaire',
    category: 'Armure',
    imageUrl: `${WIKI}Solar_Flare_Helmet.png`,
    stats: { defense: 26 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'solar_wings',
    name: 'Ailes solaires',
    category: 'Accessoire',
    imageUrl: `${WIKI}Solar_Wings.png`,
    stats: { tooltip: 'Vol ultime' },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'sonar',
    name: 'Potion de sonar',
    category: 'Potion',
    imageUrl: `${WIKI}Sonar.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'sorcerer_emblem',
    name: 'Emblème du sorcier',
    category: 'Accessoire',
    imageUrl: `${WIKI}Sorcerer_Emblem.png`,
    stats: { tooltip: '+15% dégâts magiques' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'soul_of_flight',
    name: 'Âme de vol',
    category: 'Accessoire',
    imageUrl: `${DRIVE}1rBcIDJV0lmKctTbJKE6mmx45Zq-i5DmT`,
    stats: { tooltip: 'Matériau de craft' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Minage',
  },
  {
    id: 'soul_of_fright',
    name: 'Âme de terreur',
    category: 'Accessoire',
    imageUrl: `${DRIVE}1SSodDIcuNxiKc6kIYsze7uuWjdHM99eP`,
    stats: { tooltip: 'Matériau de craft' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'soul_of_light',
    name: 'Âme de lumière',
    category: 'Accessoire',
    imageUrl: `${DRIVE}1hFhtUQqARMrOEAsdxTc6EbnvysoCFlr_`,
    stats: { tooltip: 'Matériau de craft' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Minage',
  },
  {
    id: 'soul_of_might',
    name: 'Âme de puissance',
    category: 'Accessoire',
    imageUrl: `${DRIVE}1HUDyuN_NqKafvaiFiw5dbuTVH8xPYlQq`,
    stats: { tooltip: 'Matériau de craft' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'soul_of_night',
    name: 'Âme des ténèbres',
    category: 'Accessoire',
    imageUrl: `${DRIVE}1yydeEUmwTijra6ZAfUMl6Du6qz3hwpbo`,
    stats: { tooltip: 'Matériau de craft' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Minage',
  },
  {
    id: 'soul_of_sight',
    name: 'Âme de vision',
    category: 'Accessoire',
    imageUrl: `${DRIVE}18I2VWmGHTFmLkp0cnh037M2rVZCYUzp9`,
    stats: { tooltip: 'Matériau de craft' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'space_gun',
    name: 'Fusil spatial',
    category: 'Arme',
    imageUrl: `${WIKI}Space_Gun.png`,
    stats: { damage: 17 },
    ingredients: undefined,
    tier: 'Météore',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'spectre_boots',
    name: 'Bottes spectrales',
    category: 'Accessoire',
    imageUrl: `${WIKI}Spectre_Boots.png`,
    stats: { tooltip: 'Course + vol' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'spectre_chest',
    name: 'Plastron spectre',
    category: 'Armure',
    imageUrl: `${WIKI}Spectre_Chest.png`,
    stats: { defense: 14 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'spectre_greaves',
    name: 'Jambières spectre',
    category: 'Armure',
    imageUrl: `${WIKI}Spectre_Greaves.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'spectre_helmet',
    name: 'Casque spectre',
    category: 'Armure',
    imageUrl: `${WIKI}Spectre_Helmet.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'spectre_pickaxe',
    name: 'Pioche spectre',
    category: 'Outil',
    imageUrl: `${DRIVE}1qO0ICR_ltWTOwI6z8OJK8U6ICRWs4JW-`,
    stats: { damage: 14, pickaxePower: 200 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'spectre_staff',
    name: 'Bâton spectre',
    category: 'Arme',
    imageUrl: `${WIKI}Spectre_Staff.png`,
    stats: { damage: 68 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'spelunker',
    name: 'Potion de spéléologue',
    category: 'Potion',
    imageUrl: `${WIKI}Spelunker.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'spooky_wings',
    name: 'Ailes spectrales',
    category: 'Accessoire',
    imageUrl: `${WIKI}Spooky_Wings.png`,
    stats: { tooltip: 'Vol avancé' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'star_wrath',
    name: 'Courroux des étoiles',
    category: 'Arme',
    imageUrl: `${WIKI}Star_Wrath.png`,
    stats: { damage: 110, speed: 15 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Butin',
  },
  {
    id: 'stardust_chest',
    name: 'Plastron de poussière d\'étoiles',
    category: 'Armure',
    imageUrl: `${WIKI}Stardust_Chest.png`,
    stats: { defense: 12 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'stardust_greaves',
    name: 'Jambières de poussière d\'étoiles',
    category: 'Armure',
    imageUrl: `${WIKI}Stardust_Greaves.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'stardust_helmet',
    name: 'Casque de poussière d\'étoiles',
    category: 'Armure',
    imageUrl: `${WIKI}Stardust_Helmet.png`,
    stats: { defense: 8 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'stardust_wings',
    name: 'Ailes de poussière d\'étoiles',
    category: 'Accessoire',
    imageUrl: `${WIKI}Stardust_Wings.png`,
    stats: { tooltip: 'Vol ultime' },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'steampunk_wings',
    name: 'Ailes steampunk',
    category: 'Accessoire',
    imageUrl: `${WIKI}Steampunk_Wings.png`,
    stats: { tooltip: 'Vol avancé' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'summoner_emblem',
    name: 'Emblème de l\'invocateur',
    category: 'Accessoire',
    imageUrl: `${WIKI}Summoner_Emblem.png`,
    stats: { tooltip: '+15% dégâts invocation' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'summoning',
    name: 'Potion d\'invocation',
    category: 'Potion',
    imageUrl: `${WIKI}Summoning.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'super_healing',
    name: 'Super potion de soin',
    category: 'Potion',
    imageUrl: `${WIKI}Super_Healing.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'super_mana',
    name: 'Super potion de mana',
    category: 'Potion',
    imageUrl: `${WIKI}Super_Mana.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Bouteille',
  },
  {
    id: 'swiftness',
    name: 'Potion de rapidité',
    category: 'Potion',
    imageUrl: `${WIKI}Swiftness.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'teleportation',
    name: 'Potion de téléportation',
    category: 'Potion',
    imageUrl: `${WIKI}Teleportation.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'tendon_bow',
    name: 'Arc en tendon',
    category: 'Arme',
    imageUrl: `${WIKI}Tendon_Bow.png`,
    stats: { damage: 17 },
    ingredients: undefined,
    tier: 'Crimson',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'terra_blade',
    name: 'Lame Terra',
    category: 'Arme',
    imageUrl: `${WIKI}Terra_Blade.png`,
    stats: { damage: 85, speed: 16 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'terraspark_boots',
    name: 'Bottes Terraspéciales',
    category: 'Accessoire',
    imageUrl: `${WIKI}Terraspark_Boots.png`,
    stats: { tooltip: 'Course ultime + lave + glace' },
    ingredients: undefined,
    tier: 'Avancé',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'the_hammer_night',
    name: 'Marteau de la nuit',
    category: 'Outil',
    imageUrl: `${WIKI}The_Hammer_of_the_Night.png`,
    stats: { damage: 17 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'tin_axe',
    name: 'Hache en étain',
    category: 'Outil',
    imageUrl: `${DRIVE}1aFkOEkQKazj7qyVCMw0fr76-CnvnZ8E6`,
    stats: { damage: 5 },
    ingredients: undefined,
    tier: 'Étain',
    craftedAt: 'Établi',
  },
  {
    id: 'tin_bar',
    name: 'Lingot d\'étain',
    category: 'Ressource',
    imageUrl: `${DRIVE}12YVBtvUuRh3KcHCAxa6SmaVscAqPlt2U`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Étain',
    craftedAt: 'Fourneau',
  },
  {
    id: 'tin_hammer',
    name: 'Marteau en étain',
    category: 'Outil',
    imageUrl: `${DRIVE}1f2xuGPnENnOk9dLoeM5KGegS8EBDuu_i`,
    stats: { damage: 6 },
    ingredients: undefined,
    tier: 'Étain',
    craftedAt: 'Établi',
  },
  {
    id: 'tin_ore',
    name: 'Minerai d\'étain',
    category: 'Ressource',
    imageUrl: `${DRIVE}1u5SPR5CoyVkUz0H8y3VTJ3kt-fz1mzqi`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Étain',
    craftedAt: undefined,
  },
  {
    id: 'tin_pickaxe',
    name: 'Pioche en étain',
    category: 'Outil',
    imageUrl: `${DRIVE}1OZWeDtD46TCMywBk81QN1T0xfqpzEe2x`,
    stats: { damage: 5, pickaxePower: 38 },
    ingredients: undefined,
    tier: 'Étain',
    craftedAt: 'Établi',
  },
  {
    id: 'tin_sword',
    name: 'Épée en étain',
    category: 'Arme',
    imageUrl: `${WIKI}Tin_Broadsword.png`,
    stats: { damage: 10, speed: 20 },
    ingredients: undefined,
    tier: 'Étain',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'tinkerer_workshop',
    name: 'Atelier du bricoleur',
    category: 'Station de craft',
    imageUrl: `${WIKI}Tinkerer%27s_Workshop.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'titanium_bar',
    name: 'Lingot de titane',
    category: 'Ressource',
    imageUrl: `${DRIVE}1zYUNr1SNY3BI4lX8ak30cR2Y7nBZNxr7`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Forge d\'adamantite',
  },
  {
    id: 'titanium_ore',
    name: 'Minerai de titane',
    category: 'Ressource',
    imageUrl: `${DRIVE}1GZUym8UCiKAKqN0p9MpxV1_XYvCwYlIG`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: undefined,
  },
  {
    id: 'titanium_pickaxe',
    name: 'Pioche en titane',
    category: 'Outil',
    imageUrl: `${DRIVE}1Mn4-6RWOFXHhpCKnr6UmKN1IdImzcW9G`,
    stats: { damage: 12, pickaxePower: 190 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'topaz_staff',
    name: 'Bâton de topaze',
    category: 'Arme',
    imageUrl: `${WIKI}Topaz_Staff.png`,
    stats: { damage: 16 },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'true_excalibur',
    name: 'Vraie Excalibur',
    category: 'Arme',
    imageUrl: `${WIKI}True_Excalibur.png`,
    stats: { damage: 72, speed: 22 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'true_nights_edge',
    name: 'Vraie épée des ténèbres',
    category: 'Arme',
    imageUrl: `${WIKI}True_Nights_Edge.png`,
    stats: { damage: 70, speed: 22 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'tsunami',
    name: 'Tsunami',
    category: 'Arme',
    imageUrl: `${WIKI}Tsunami.png`,
    stats: { damage: 60 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'tsunami_in_a_bottle',
    name: 'Tsunami en bouteille',
    category: 'Accessoire',
    imageUrl: `${WIKI}Tsunami_In_A_Bottle.png`,
    stats: { tooltip: 'Triple saut' },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'tungsten_axe',
    name: 'Hache en tungstène',
    category: 'Outil',
    imageUrl: `${DRIVE}15CGuyQItyQv8OgnXTU76-_lHZ5Tj8KHa`,
    stats: { damage: 9 },
    ingredients: undefined,
    tier: 'Tungstène',
    craftedAt: 'Établi',
  },
  {
    id: 'tungsten_bar',
    name: 'Lingot de tungstène',
    category: 'Ressource',
    imageUrl: `${DRIVE}1wn07lsuhR2g0YCrAQ78bQOhxupXgraZZ`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Tungstène',
    craftedAt: 'Fourneau',
  },
  {
    id: 'tungsten_hammer',
    name: 'Marteau en tungstène',
    category: 'Outil',
    imageUrl: `${DRIVE}1Spy1Ip3NvDN7ht-ObKBX0SXf4zDVo86C`,
    stats: { damage: 10 },
    ingredients: undefined,
    tier: 'Tungstène',
    craftedAt: 'Établi',
  },
  {
    id: 'tungsten_ore',
    name: 'Minerai de tungstène',
    category: 'Ressource',
    imageUrl: `${DRIVE}1Ztm-BN-rOSYQoDa3MEsvhw2vzFtIDXmt`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Tungstène',
    craftedAt: undefined,
  },
  {
    id: 'tungsten_pickaxe',
    name: 'Pioche en tungstène',
    category: 'Outil',
    imageUrl: `${DRIVE}1LeZ7vbLioSCnNgmkVxFIHIj4GTdrOCbL`,
    stats: { damage: 9, pickaxePower: 70 },
    ingredients: undefined,
    tier: 'Tungstène',
    craftedAt: 'Établi',
  },
  {
    id: 'tungsten_sword',
    name: 'Épée en tungstène',
    category: 'Arme',
    imageUrl: `${WIKI}Tungsten_Broadsword.png`,
    stats: { damage: 15, speed: 18 },
    ingredients: undefined,
    tier: 'Tungstène',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'turtle_chest',
    name: 'Plastron en tortue',
    category: 'Armure',
    imageUrl: `${WIKI}Turtle_Chest.png`,
    stats: { defense: 21 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'turtle_greaves',
    name: 'Jambières en tortue',
    category: 'Armure',
    imageUrl: `${WIKI}Turtle_Greaves.png`,
    stats: { defense: 14 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'turtle_helmet',
    name: 'Casque en tortue',
    category: 'Armure',
    imageUrl: `${WIKI}Turtle_Helmet.png`,
    stats: { defense: 16 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Enclume de mithril',
  },
  {
    id: 'uzy',
    name: 'Uzi',
    category: 'Arme',
    imageUrl: `${WIKI}Uzy.png`,
    stats: { damage: 30 },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'vortex_beater',
    name: 'Mitrailleuse vortex',
    category: 'Arme',
    imageUrl: `${WIKI}Vortex_Beater.png`,
    stats: { damage: 50 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'vortex_chest',
    name: 'Plastron de vortex',
    category: 'Armure',
    imageUrl: `${WIKI}Vortex_Chest.png`,
    stats: { defense: 17 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'vortex_greaves',
    name: 'Jambières de vortex',
    category: 'Armure',
    imageUrl: `${WIKI}Vortex_Greaves.png`,
    stats: { defense: 11 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'vortex_helmet',
    name: 'Casque de vortex',
    category: 'Armure',
    imageUrl: `${WIKI}Vortex_Helmet.png`,
    stats: { defense: 10 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume ancienne',
  },
  {
    id: 'vortex_wings',
    name: 'Ailes de vortex',
    category: 'Accessoire',
    imageUrl: `${WIKI}Vortex_Wings.png`,
    stats: { tooltip: 'Vol ultime' },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Atelier du bricoleur',
  },
  {
    id: 'wand_of_sparking',
    name: 'Baguette d\'étincelles',
    category: 'Arme',
    imageUrl: `${WIKI}Wand_Of_Sparking.png`,
    stats: { damage: 14 },
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Butin',
  },
  {
    id: 'war_axe_night',
    name: 'Hache de guerre de la nuit',
    category: 'Outil',
    imageUrl: `${WIKI}War_Axe_of_the_Night.png`,
    stats: { damage: 13 },
    ingredients: undefined,
    tier: 'Corruption',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'warmth',
    name: 'Potion de chaleur',
    category: 'Potion',
    imageUrl: `${WIKI}Warmth.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'warrior_emblem',
    name: 'Emblème du guerrier',
    category: 'Accessoire',
    imageUrl: `${WIKI}Warrior_Emblem.png`,
    stats: { tooltip: '+15% dégâts mêlée' },
    ingredients: undefined,
    tier: 'Hardmode',
    craftedAt: 'Butin',
  },
  {
    id: 'water_bolt',
    name: 'Éclat d\'eau',
    category: 'Arme',
    imageUrl: `${WIKI}Water_Bolt.png`,
    stats: { damage: 19 },
    ingredients: undefined,
    tier: 'Donjon',
    craftedAt: 'Butin',
  },
  {
    id: 'water_walking',
    name: 'Potion de marche sur l\'eau',
    category: 'Potion',
    imageUrl: `${WIKI}Water_Walking.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Bouteille',
  },
  {
    id: 'wood_chest',
    name: 'Plastron en bois',
    category: 'Armure',
    imageUrl: `${WIKI}Wood_Breastplate.png`,
    stats: { defense: 3 },
    ingredients: undefined,
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'wood_greaves',
    name: 'Jambières en bois',
    category: 'Armure',
    imageUrl: `${WIKI}Wood_Greaves.png`,
    stats: { defense: 2 },
    ingredients: undefined,
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'wood_helmet',
    name: 'Casque en bois',
    category: 'Armure',
    imageUrl: `${WIKI}Wood_Helmet.png`,
    stats: { defense: 2 },
    ingredients: undefined,
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'wooden_bow',
    name: 'Arc en bois',
    category: 'Arme',
    imageUrl: `${WIKI}Wooden_Bow.png`,
    stats: { damage: 4 },
    ingredients: undefined,
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'wooden_sword',
    name: 'Épée en bois',
    category: 'Arme',
    imageUrl: `${WIKI}Wooden_Sword.png`,
    stats: { damage: 8, speed: 20 },
    ingredients: undefined,
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'workbench',
    name: 'Établi',
    category: 'Station de craft',
    imageUrl: `${WIKI}Work_Bench.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Début',
    craftedAt: 'Inventaire',
  },
  {
    id: 'wrath',
    name: 'Potion de courroux',
    category: 'Potion',
    imageUrl: `${WIKI}Wrath.png`,
    stats: undefined,
    ingredients: undefined,
    tier: 'Corruption',
    craftedAt: 'Bouteille',
  },
  {
    id: 'zenith',
    name: 'Zénith',
    category: 'Arme',
    imageUrl: `${WIKI}Zenith.png`,
    stats: { damage: 190, speed: 30 },
    ingredients: undefined,
    tier: 'Fin',
    craftedAt: 'Enclume de mithril',
  },
];