import { CraftingItem } from './types';

// ============================================
// TERRARIA CRAFT HELPER — Item Database
// Icônes originales scrappées du Terraria Wiki
// ============================================

// Helper: icon from Google Drive (public, scraped from wiki)
const DRIVE_BASE = 'https://drive.google.com/uc?export=view&id=';

export const itemsData: CraftingItem[] = [
  // ═══════════════════════════════════════════
  //   ARMES — Épées longues (Broadswords)
  // ═══════════════════════════════════════════
  {
    id: 'wooden_sword',
    name: 'Épée en bois',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Wooden_Sword.png',
    stats: { damage: 8, speed: 20, tooltip: 'Une épée en bois de base.' },
    ingredients: [{ name: 'Bois', quantity: 7 }],
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'cactus_sword',
    name: 'Épée en cactus',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Cactus_Sword.png',
    stats: { damage: 10, speed: 20, tooltip: 'Une épée piquante.' },
    ingredients: [{ name: 'Cactus', quantity: 10 }],
    tier: 'Cactus',
    craftedAt: 'Établi',
  },
  {
    id: 'copper_sword',
    name: 'Épée en cuivre',
    category: 'Arme',
    imageUrl: `${DRIVE_BASE}1zCbXp0LJLGN6EHgU3ZVoXCufp8KTv4Sj`,
    stats: { damage: 9, speed: 21, tooltip: 'Une épée de base.' },
    ingredients: [{ name: 'Barre de cuivre', quantity: 7 }],
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'tin_sword',
    name: 'Épée en étain',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Tin_Broadsword.png',
    stats: { damage: 10, speed: 20, tooltip: 'Légèrement mieux que le cuivre.' },
    ingredients: [{ name: "Barre d'étain", quantity: 7 }],
    tier: 'Étain',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_sword',
    name: 'Épée en fer',
    category: 'Arme',
    imageUrl: `${DRIVE_BASE}1HHpn8on9ZmPOO4OyGjoP0KebgDObVljf`,
    stats: { damage: 13, speed: 20, tooltip: 'Une épée en fer solide.' },
    ingredients: [{ name: 'Barre de fer', quantity: 8 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'lead_sword',
    name: 'Épée en plomb',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Lead_Broadsword.png',
    stats: { damage: 14, speed: 19, tooltip: 'Alternative au fer.' },
    ingredients: [{ name: 'Barre de plomb', quantity: 8 }],
    tier: 'Plomb',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'silver_sword',
    name: 'Épée en argent',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Silver_Broadsword.png',
    stats: { damage: 14, speed: 19, tooltip: 'Brille dans le noir.' },
    ingredients: [{ name: "Barre d'argent", quantity: 8 }],
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'tungsten_sword',
    name: 'Épée en tungstène',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Tungsten_Broadsword.png',
    stats: { damage: 15, speed: 18, tooltip: 'Un métal lourd et solide.' },
    ingredients: [{ name: 'Barre de tungstène', quantity: 8 }],
    tier: 'Tungstène',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'gold_sword',
    name: 'Épée en or',
    category: 'Arme',
    imageUrl: `${DRIVE_BASE}1kNe_pCS37XARUvwX2JE1-lv2nzAp3sjf`,
    stats: { damage: 15, speed: 18, tooltip: 'Plus tranchante que le fer.' },
    ingredients: [{ name: "Barre d'or", quantity: 8 }],
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'platinum_sword',
    name: 'Épée en platine',
    category: 'Arme',
    imageUrl: `${DRIVE_BASE}1KiWy6dl7NEVuAvt1bh6ooBqhMOUZD6JZ`,
    stats: { damage: 16, speed: 17, tooltip: 'Le meilleur des métaux de base.' },
    ingredients: [{ name: 'Barre de platine', quantity: 8 }],
    tier: 'Platine',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'light_bane',
    name: 'Fléau des ténèbres',
    category: 'Arme',
    imageUrl: `${DRIVE_BASE}1bHU6SHkpUhRkGgsswzFtAh2o-TeEsaFH`,
    stats: { damage: 17, speed: 19, tooltip: "L'arme des ténèbres." },
    ingredients: [{ name: "Barre d'écorce démoniaque", quantity: 10 }],
    tier: 'Corruption',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'blood_butcherer',
    name: 'Éventreur sanguinaire',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Blood_Butcherer.png',
    stats: { damage: 22, speed: 19, tooltip: "L'alternative cramoisie." },
    ingredients: [{ name: 'Barre de crimtane', quantity: 10 }],
    tier: 'Crimson',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'fiery_greatsword',
    name: 'Épée de feu',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Fiery_Greatsword.png',
    stats: { damage: 36, speed: 29, tooltip: 'Chaînes en fusion.' },
    ingredients: [{ name: 'Barre infernale', quantity: 20 }],
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'blade_of_grass',
    name: 'Lame d\'herbe',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Blade_of_Grass.png',
    stats: { damage: 28, speed: 25, tooltip: 'Infestée de venin.' },
    ingredients: [
      { name: 'Lame de roseau', quantity: 15 },
      { name: 'Vigne', quantity: 12 },
      { name: 'Épine du jungle', quantity: 3 },
    ],
    tier: 'Jungle',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'muramasa',
    name: 'Muramasa',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Muramasa.png',
    stats: { damage: 24, speed: 18, tooltip: 'Lame bleue du donjon.' },
    ingredients: [{ name: 'Trouvée dans le Donjon', quantity: 1 }],
    tier: 'Donjon',
    craftedAt: 'Butin',
  },
  {
    id: 'enchanted_sword',
    name: 'Épée enchantée',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Enchanted_Sword.png',
    stats: { damage: 23, speed: 21, tooltip: 'Tir laser !' },
    ingredients: [{ name: 'Trouvée dans des sanctuaires', quantity: 1 }],
    tier: 'Spécial',
    craftedAt: 'Butin',
  },
  {
    id: 'nights_edge',
    name: 'Épée des ténèbres',
    category: 'Arme',
    imageUrl: 'https://terraria.wiki.gg/images/Nights_Edge.png',
    stats: { damage: 42, speed: 19, tooltip: 'L\'ultime épée pré-Hardmode.' },
    ingredients: [
      { name: 'Lame d\'herbe', quantity: 1 },
      { name: 'Muramasa', quantity: 1 },
      { name: 'Fléau des ténèbres', quantity: 1 },
      { name: 'Éventreur sanguinaire', quantity: 1 },
    ],
    tier: 'Avancé',
    craftedAt: 'Enclume d\'enfer',
  },

  // ═══════════════════════════════════════════
  //   ARMURES — Palier par palier
  // ═══════════════════════════════════════════

  // --- Bois ---
  {
    id: 'wood_helmet',
    name: 'Casque en bois',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Wood_Helmet.png',
    stats: { defense: 2, tooltip: 'Protection basique.' },
    ingredients: [{ name: 'Bois', quantity: 15 }],
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'wood_chest',
    name: 'Armure en bois',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Wood_Breastplate.png',
    stats: { defense: 3, tooltip: 'Protection basique.' },
    ingredients: [{ name: 'Bois', quantity: 20 }],
    tier: 'Bois',
    craftedAt: 'Établi',
  },
  {
    id: 'wood_greaves',
    name: 'Jambières en bois',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Wood_Greaves.png',
    stats: { defense: 2, tooltip: 'Protection basique.' },
    ingredients: [{ name: 'Bois', quantity: 10 }],
    tier: 'Bois',
    craftedAt: 'Établi',
  },

  // --- Cuivre ---
  {
    id: 'copper_helmet',
    name: 'Casque en cuivre',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Copper_Helmet.png',
    stats: { defense: 2, tooltip: 'Première armure métallique.' },
    ingredients: [{ name: 'Barre de cuivre', quantity: 5 }],
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'copper_chest',
    name: 'Plastron en cuivre',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Copper_Chainmail.png',
    stats: { defense: 3, tooltip: 'Protège le torse.' },
    ingredients: [{ name: 'Barre de cuivre', quantity: 8 }],
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'copper_greaves',
    name: 'Jambières en cuivre',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Copper_Greaves.png',
    stats: { defense: 2, tooltip: 'Protège les jambes.' },
    ingredients: [{ name: 'Barre de cuivre', quantity: 6 }],
    tier: 'Cuivre',
    craftedAt: 'Enclume de fer',
  },

  // --- Fer ---
  {
    id: 'iron_helmet',
    name: 'Casque en fer',
    category: 'Armure',
    imageUrl: `${DRIVE_BASE}1HuY9ydk6Qw767m341UJHrjW3JYKW_O6y`,
    stats: { defense: 3, tooltip: "Partie de l'armure en fer." },
    ingredients: [{ name: 'Barre de fer', quantity: 5 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_chest',
    name: 'Plastron en fer',
    category: 'Armure',
    imageUrl: `${DRIVE_BASE}1BSXxo3bvg_Rf9xBBgarja8B_fa56IbNu`,
    stats: { defense: 4, tooltip: 'Protège le torse.' },
    ingredients: [{ name: 'Barre de fer', quantity: 8 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'iron_greaves',
    name: 'Jambières en fer',
    category: 'Armure',
    imageUrl: `${DRIVE_BASE}1CdDKdnXzBTrvjtzU-0Y9Jsr9q3Uf1M33`,
    stats: { defense: 3, tooltip: 'Protège les jambes.' },
    ingredients: [{ name: 'Barre de fer', quantity: 6 }],
    tier: 'Fer',
    craftedAt: 'Enclume de fer',
  },

  // --- Argent ---
  {
    id: 'silver_helmet',
    name: 'Casque en argent',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Silver_Helmet.png',
    stats: { defense: 3, tooltip: 'Casque argenté brillant.' },
    ingredients: [{ name: "Barre d'argent", quantity: 5 }],
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'silver_chest',
    name: 'Plastron en argent',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Silver_Chainmail.png',
    stats: { defense: 4, tooltip: 'Brille de mille feux.' },
    ingredients: [{ name: "Barre d'argent", quantity: 8 }],
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'silver_greaves',
    name: 'Jambières en argent',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Silver_Greaves.png',
    stats: { defense: 3, tooltip: 'Jambières argentées.' },
    ingredients: [{ name: "Barre d'argent", quantity: 6 }],
    tier: 'Argent',
    craftedAt: 'Enclume de fer',
  },

  // --- Or ---
  {
    id: 'gold_helmet',
    name: 'Casque en or',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Gold_Helmet.png',
    stats: { defense: 4, tooltip: 'Casque doré étincelant.' },
    ingredients: [{ name: "Barre d'or", quantity: 5 }],
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'gold_chest',
    name: 'Plastron en or',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Gold_Chainmail.png',
    stats: { defense: 5, tooltip: 'Brille comme le soleil.' },
    ingredients: [{ name: "Barre d'or", quantity: 8 }],
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'gold_greaves',
    name: 'Jambières en or',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Gold_Greaves.png',
    stats: { defense: 3, tooltip: 'Jambières luxueuses.' },
    ingredients: [{ name: "Barre d'or", quantity: 6 }],
    tier: 'Or',
    craftedAt: 'Enclume de fer',
  },

  // --- Ombre ---
  {
    id: 'shadow_helmet',
    name: 'Casque de l\'ombre',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Shadow_Helmet.png',
    stats: { defense: 6, tooltip: 'Casque des ténèbres.' },
    ingredients: [{ name: "Barre d'écorce démoniaque", quantity: 10 }],
    tier: 'Ombre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'shadow_chest',
    name: 'Plastron de l\'ombre',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Shadow_Scale_Mail.png',
    stats: { defense: 7, tooltip: 'Armure écailleuse des ténèbres.' },
    ingredients: [{ name: "Barre d'écorce démoniaque", quantity: 15 }],
    tier: 'Ombre',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'shadow_greaves',
    name: 'Jambières de l\'ombre',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Shadow_Greaves.png',
    stats: { defense: 5, tooltip: 'Jambières des ténèbres.' },
    ingredients: [{ name: "Barre d'écorce démoniaque", quantity: 8 }],
    tier: 'Ombre',
    craftedAt: 'Enclume de fer',
  },

  // --- Fusion (Molten) ---
  {
    id: 'molten_helmet',
    name: 'Casque en fusion',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Molten_Helmet.png',
    stats: { defense: 8, tooltip: 'Casque de lave solidifiée.' },
    ingredients: [{ name: 'Barre infernale', quantity: 10 }],
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'molten_chest',
    name: 'Plastron en fusion',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Molten_Breastplate.png',
    stats: { defense: 9, tooltip: 'Bouillant de puissance.' },
    ingredients: [{ name: 'Barre infernale', quantity: 15 }],
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },
  {
    id: 'molten_greaves',
    name: 'Jambières en fusion',
    category: 'Armure',
    imageUrl: 'https://terraria.wiki.gg/images/Molten_Greaves.png',
    stats: { defense: 7, tooltip: 'Marche dans la lave.' },
    ingredients: [{ name: 'Barre infernale', quantity: 8 }],
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },

  // ═══════════════════════════════════════════
  //   OUTILS — Pioches
  // ═══════════════════════════════════════════

  {
    id: 'copper_pickaxe',
    name: 'Pioche en cuivre',
    category: 'Outil',
    imageUrl: `${DRIVE_BASE}1Ch8XZxffIn91Zpznz057dDifFroSOvRL`,
    stats: { pickaxePower: 35, damage: 4, tooltip: 'Permet de miner les blocs de base.' },
    ingredients: [
      { name: 'Barre de cuivre', quantity: 6 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Cuivre',
    craftedAt: 'Établi',
  },
  {
    id: 'tin_pickaxe',
    name: 'Pioche en étain',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/images/Tin_Pickaxe.png',
    stats: { pickaxePower: 38, damage: 5, tooltip: 'Un peu mieux que le cuivre.' },
    ingredients: [
      { name: "Barre d'étain", quantity: 6 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Étain',
    craftedAt: 'Établi',
  },
  {
    id: 'iron_pickaxe',
    name: 'Pioche en fer',
    category: 'Outil',
    imageUrl: `${DRIVE_BASE}1hOpUwMmrReGvADDQGq0oQ5tztUZTZclX`,
    stats: { pickaxePower: 55, damage: 6, tooltip: 'Mine plus efficacement.' },
    ingredients: [
      { name: 'Barre de fer', quantity: 8 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'lead_pickaxe',
    name: 'Pioche en plomb',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/images/Lead_Pickaxe.png',
    stats: { pickaxePower: 59, damage: 7, tooltip: 'Alternative au fer.' },
    ingredients: [
      { name: 'Barre de plomb', quantity: 8 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Plomb',
    craftedAt: 'Établi',
  },
  {
    id: 'silver_pickaxe',
    name: 'Pioche en argent',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/images/Silver_Pickaxe.png',
    stats: { pickaxePower: 65, damage: 8, tooltip: 'Pioche argentée efficace.' },
    ingredients: [
      { name: "Barre d'argent", quantity: 8 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Argent',
    craftedAt: 'Établi',
  },
  {
    id: 'gold_pickaxe',
    name: 'Pioche en or',
    category: 'Outil',
    imageUrl: `${DRIVE_BASE}1Xa0VkEmfouC_3Q90n4Onfga-eOLQCSjC`,
    stats: { pickaxePower: 65, damage: 7, tooltip: 'Encore plus efficace.' },
    ingredients: [
      { name: "Barre d'or", quantity: 8 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Or',
    craftedAt: 'Établi',
  },
  {
    id: 'platinum_pickaxe',
    name: 'Pioche en platine',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/images/Platinum_Pickaxe.png',
    stats: { pickaxePower: 70, damage: 9, tooltip: 'Le meilleur des métaux de base.' },
    ingredients: [
      { name: 'Barre de platine', quantity: 8 },
      { name: 'Bois', quantity: 3 },
    ],
    tier: 'Platine',
    craftedAt: 'Établi',
  },
  {
    id: 'deathbringer_pickaxe',
    name: 'Pioche de mort',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/images/Deathbringer_Pickaxe.png',
    stats: { pickaxePower: 55, damage: 8, tooltip: 'Pioche démoniaque.' },
    ingredients: [
      { name: "Barre d'écorce démoniaque", quantity: 12 },
      { name: 'Bois', quantity: 4 },
    ],
    tier: 'Corruption',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'nightmare_pickaxe',
    name: 'Pioche de cauchemar',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/images/Nightmare_Pickaxe.png',
    stats: { pickaxePower: 55, damage: 9, tooltip: 'Pioche cramoisie.' },
    ingredients: [
      { name: 'Barre de crimtane', quantity: 12 },
      { name: 'Bois', quantity: 4 },
    ],
    tier: 'Crimson',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'molten_pickaxe',
    name: 'Pioche en fusion',
    category: 'Outil',
    imageUrl: 'https://terraria.wiki.gg/images/Molten_Pickaxe.png',
    stats: { pickaxePower: 100, damage: 12, tooltip: 'La meilleure pioche pré-Hardmode.' },
    ingredients: [
      { name: 'Barre infernale', quantity: 15 },
    ],
    tier: 'Enfer',
    craftedAt: 'Enclume d\'enfer',
  },

  // ═══════════════════════════════════════════
  //   STATIONS DE CRAFT
  // ═══════════════════════════════════════════

  {
    id: 'workbench',
    name: 'Établi',
    category: 'Station de craft',
    imageUrl: `${DRIVE_BASE}1O0oZKHXKMN2o8ta9QOoEJJlchTghw5vO`,
    stats: { tooltip: 'Station de craft essentielle pour débuter.' },
    ingredients: [{ name: 'Bois', quantity: 10 }],
    tier: 'Début',
    craftedAt: 'Inventaire',
  },
  {
    id: 'furnace',
    name: 'Fourneau',
    category: 'Station de craft',
    imageUrl: `${DRIVE_BASE}1vaFYItunFx0EThOjABE9URw6dCGb8XhM`,
    stats: { tooltip: 'Permet de fondre les minerais en barres.' },
    ingredients: [
      { name: 'Pierre', quantity: 20 },
      { name: 'Bois', quantity: 4 },
      { name: 'Torche', quantity: 3 },
    ],
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'anvil',
    name: 'Enclume de fer',
    category: 'Station de craft',
    imageUrl: `${DRIVE_BASE}1jmKiA2ST3Wd_W_e4W60V_utojg9EV86x`,
    stats: { tooltip: 'Permet de forger des armes et armures.' },
    ingredients: [{ name: 'Barre de fer', quantity: 5 }],
    tier: 'Fer',
    craftedAt: 'Établi',
  },
  {
    id: 'hellforge',
    name: 'Enfernoir',
    category: 'Station de craft',
    imageUrl: `${DRIVE_BASE}1T4h7_8ikjZRmRDaRPzytiXDBBBomTcaD`,
    stats: { tooltip: "Fusionne le minerai d'enfer." },
    ingredients: [{ name: 'Fourneau', quantity: 1 }],
    tier: 'Enfer',
    craftedAt: 'Établi',
  },
  {
    id: 'loom',
    name: 'Métier à tisser',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/images/Loom.png',
    stats: { tooltip: 'Permet de fabriquer de la soie.' },
    ingredients: [
      { name: 'Bois', quantity: 12 },
    ],
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'sawmill',
    name: 'Scierie',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/images/Sawmill.png',
    stats: { tooltip: "Permet de fabriquer des meubles avancés." },
    ingredients: [
      { name: 'Bois', quantity: 10 },
      { name: 'Barre de fer', quantity: 2 },
      { name: 'Chaîne', quantity: 1 },
    ],
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'tinkerer_workshop',
    name: 'Atelier du bricoleur',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/images/Tinkerer%27s_Workshop.png',
    stats: { tooltip: "Permet de combiner des accessoires." },
    ingredients: [
      { name: 'Barre de fer', quantity: 10 },
      { name: 'Bois', quantity: 5 },
    ],
    tier: 'Début',
    craftedAt: 'Établi',
  },
  {
    id: 'mythril_anvil',
    name: 'Enclume de mithril',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/images/Mythril_Anvil.png',
    stats: { tooltip: 'Enclume avancée du Hardmode.' },
    ingredients: [{ name: 'Barre de mithril', quantity: 10 }],
    tier: 'Hardmode',
    craftedAt: 'Enclume de fer',
  },
  {
    id: 'adamantite_forge',
    name: 'Forge d\'adamantite',
    category: 'Station de craft',
    imageUrl: 'https://terraria.wiki.gg/images/Adamantite_Forge.png',
    stats: { tooltip: "Fusionne les minerais du Hardmode." },
    ingredients: [{ name: 'Barre d\'adamantite', quantity: 10 }],
    tier: 'Hardmode',
    craftedAt: 'Enfernoir',
  },
];