export type NpcPhase = 'pre-hardmode' | 'hardmode' | 'flexible'
export type NpcStatus = 'excellent' | 'correct' | 'avoid'

export interface NpcData {
  id: string
  name: string
  biome: string
  partner: string
  role: string
  priority: number
  notes: string
  phase: NpcPhase
  utility: string[]
  mustHave: boolean
  pylonTarget: string
  status: NpcStatus
  emoji: string
}

export interface VillageGroup {
  biome: string
  npcs: string[]
  pylon: string
  phase: NpcPhase
  priority: number
  description: string
  emoji: string
  color: string
}

export const NPC_DATA: NpcData[] = [
  {
    id: 'guide',
    name: 'Guide',
    biome: 'Forêt',
    partner: 'Zoologiste',
    role: 'Conseils craft — indispensable début',
    priority: 1,
    notes: 'Restent en forêt. Le Guide est utile pour les recettes. La Zoologiste vend la monture licorne.',
    phase: 'pre-hardmode',
    utility: ['craft', 'conseils'],
    mustHave: true,
    pylonTarget: 'Forêt',
    status: 'excellent',
    emoji: '📖',
  },
  {
    id: 'zoologiste',
    name: 'Zoologiste',
    biome: 'Forêt',
    partner: 'Guide',
    role: 'Montures / animaux de compagnie',
    priority: 2,
    notes: 'Arrive après 10% de bestiaire complété. Aime la forêt. Bon duo avec le Guide.',
    phase: 'pre-hardmode',
    utility: ['montures', 'animaux'],
    mustHave: true,
    pylonTarget: 'Forêt',
    status: 'excellent',
    emoji: '🐾',
  },
  {
    id: 'infirmiere',
    name: 'Infirmière',
    biome: 'Désert',
    partner: 'Marchand d\'armes',
    role: 'Soins — essentiel',
    priority: 3,
    notes: 'Soigne les joueurs contre pièces. Aime le désert avec le Marchand d\'armes. Duo prioritaire pour pylône désert.',
    phase: 'pre-hardmode',
    utility: ['soins'],
    mustHave: true,
    pylonTarget: 'Désert',
    status: 'excellent',
    emoji: '❤️',
  },
  {
    id: 'marchand-armes',
    name: 'Marchand d\'armes',
    biome: 'Désert',
    partner: 'Infirmière',
    role: 'Vente d\'armes et munitions',
    priority: 4,
    notes: 'Duo iconique avec l\'Infirmière. Aiment le désert ensemble. Meilleur pylône du jeu.',
    phase: 'pre-hardmode',
    utility: ['armes', 'munitions'],
    mustHave: true,
    pylonTarget: 'Désert',
    status: 'excellent',
    emoji: '🔫',
  },
  {
    id: 'dryade',
    name: 'Dryade',
    biome: 'Jungle',
    partner: 'Sorcier vaudou',
    role: 'Buff / détection corruption',
    priority: 5,
    notes: 'Vend des graines et détecte la pureté du monde. Aime la jungle avec le Sorcier vaudou.',
    phase: 'pre-hardmode',
    utility: ['buff', 'détection', 'graines'],
    mustHave: true,
    pylonTarget: 'Jungle',
    status: 'excellent',
    emoji: '🌿',
  },
  {
    id: 'sorcier-vaudou',
    name: 'Sorcier vaudou',
    biome: 'Jungle',
    partner: 'Dryade',
    role: 'Invocateur — armure vaudou',
    priority: 6,
    notes: 'Vend de l\'équipement invocateur. Duo parfait avec la Dryade en jungle. Pylône jungle.',
    phase: 'pre-hardmode',
    utility: ['invocation', 'armure'],
    mustHave: true,
    pylonTarget: 'Jungle',
    status: 'excellent',
    emoji: '🪄',
  },
  {
    id: 'mecano',
    name: 'Mécano',
    biome: 'Neige',
    partner: 'Gobelin bricoleur',
    role: 'Mécanismes / wiring',
    priority: 7,
    notes: 'Vend pièces mécaniques et fils. Aime la neige. Duo de rêve avec le Gobelin.',
    phase: 'pre-hardmode',
    utility: ['wiring', 'mécanismes'],
    mustHave: true,
    pylonTarget: 'Neige',
    status: 'excellent',
    emoji: '🔧',
  },
  {
    id: 'gobelin-bricoleur',
    name: 'Gobelin bricoleur',
    biome: 'Neige',
    partner: 'Mécano',
    role: 'Reforge — essentiel',
    priority: 8,
    notes: 'Reforge les armes et accessoires. Aime la neige avec la Mécano. Indispensable.',
    phase: 'pre-hardmode',
    utility: ['reforge'],
    mustHave: true,
    pylonTarget: 'Neige',
    status: 'excellent',
    emoji: '⚒️',
  },
  {
    id: 'marchand',
    name: 'Marchand',
    biome: 'Océan',
    partner: 'Pêcheur',
    role: 'Vente d\'objets de base',
    priority: 9,
    notes: 'Premier PNJ recruté. En océan avec le Pêcheur pour le pylône.',
    phase: 'pre-hardmode',
    utility: ['shop'],
    mustHave: false,
    pylonTarget: 'Océan',
    status: 'correct',
    emoji: '💰',
  },
  {
    id: 'pecheur',
    name: 'Pêcheur',
    biome: 'Océan',
    partner: 'Marchand',
    role: 'Quêtes de pêche',
    priority: 10,
    notes: 'Donne des quêtes de poisson. Aime l\'océan. Duo basique avec le Marchand.',
    phase: 'pre-hardmode',
    utility: ['pêche', 'quêtes'],
    mustHave: false,
    pylonTarget: 'Océan',
    status: 'correct',
    emoji: '🎣',
  },
  {
    id: 'demolisseur',
    name: 'Démolisseur',
    biome: 'Cavernes',
    partner: 'Tavernkeep',
    role: 'Explosifs',
    priority: 11,
    notes: 'Vend bombes et explosifs. Aime les cavernes avec le Tavernkeep. Utile pour minage.',
    phase: 'pre-hardmode',
    utility: ['explosifs'],
    mustHave: false,
    pylonTarget: 'Cavernes',
    status: 'excellent',
    emoji: '💣',
  },
  {
    id: 'tavernkeep',
    name: 'Tavernkeep',
    biome: 'Cavernes',
    partner: 'Démolisseur',
    role: 'Équipement Sentinelle / Événement',
    priority: 12,
    notes: 'Vend des bannières et objets d\'invocation. Duo Cavernes avec le Démolisseur.',
    phase: 'hardmode',
    utility: ['sentinelle', 'invocation'],
    mustHave: false,
    pylonTarget: 'Cavernes',
    status: 'excellent',
    emoji: '🍺',
  },
  {
    id: 'party-girl',
    name: 'Party Girl',
    biome: 'Hallow',
    partner: 'Magicien',
    role: 'Objets de fête / déco',
    priority: 13,
    notes: 'Vend des objets festifs. Aime le Hallow avec le Magicien.',
    phase: 'pre-hardmode',
    utility: ['déco', 'fun'],
    mustHave: false,
    pylonTarget: 'Hallow',
    status: 'excellent',
    emoji: '🎉',
  },
  {
    id: 'magicien',
    name: 'Magicien',
    biome: 'Hallow',
    partner: 'Party Girl',
    role: 'Objets magiques',
    priority: 14,
    notes: 'Vend des sorts et accessoires magiques. Duo Hallow avec la Party Girl.',
    phase: 'hardmode',
    utility: ['magie', 'sorts'],
    mustHave: false,
    pylonTarget: 'Hallow',
    status: 'excellent',
    emoji: '🔮',
  },
  {
    id: 'truffle',
    name: 'Truffle',
    biome: 'Champignon',
    partner: 'Flexible',
    role: 'Vente équipement champignon',
    priority: 15,
    notes: 'Nécessite une maison en surface de biome champignon. Aime son biome. Coloc flexible.',
    phase: 'hardmode',
    utility: ['équipement', 'monture'],
    mustHave: false,
    pylonTarget: 'Champignon',
    status: 'excellent',
    emoji: '🍄',
  },
  {
    id: 'coiffeur',
    name: 'Coiffeur',
    biome: 'Flexible',
    partner: '—',
    role: 'Coiffures',
    priority: 20,
    notes: 'Se positionne où vous voulez. Pas de préférence forte. Idéal pour compléter un biome vide.',
    phase: 'pre-hardmode',
    utility: ['cosmétique'],
    mustHave: false,
    pylonTarget: '—',
    status: 'correct',
    emoji: '💇',
  },
  {
    id: 'peintre',
    name: 'Peintre',
    biome: 'Flexible',
    partner: '—',
    role: 'Peinture / déco',
    priority: 21,
    notes: 'Vend peintures et pinceaux. Placement flexible. Peut aller dans n\'importe quel village.',
    phase: 'pre-hardmode',
    utility: ['déco'],
    mustHave: false,
    pylonTarget: '—',
    status: 'correct',
    emoji: '🎨',
  },
  {
    id: 'diable',
    name: 'Diablesse',
    biome: 'Flexible',
    partner: '—',
    role: 'Objets démoniaques / armures',
    priority: 22,
    notes: 'Arrive après avoir vaincu un boss. Aime les cavernes / enfer. Flexible.',
    phase: 'pre-hardmode',
    utility: ['armure', 'démoniaque'],
    mustHave: false,
    pylonTarget: '—',
    status: 'correct',
    emoji: '😈',
  },
  {
    id: 'santa',
    name: 'Santa',
    biome: 'Flexible',
    partner: '—',
    role: 'Objets de Noël',
    priority: 23,
    notes: 'Arrive seulement pendant le mois de décembre. Flexible.',
    phase: 'hardmode',
    utility: ['déco', 'saisonnier'],
    mustHave: false,
    pylonTarget: '—',
    status: 'correct',
    emoji: '🎅',
  },
  {
    id: 'steampunker',
    name: 'Steampunker',
    biome: 'Flexible',
    partner: '—',
    role: 'Clentaminator / solutions',
    priority: 16,
    notes: 'Arrive après un boss du Hardmode. Vends le Clentaminator. Peut aller dans plusieurs biomes.',
    phase: 'hardmode',
    utility: ['biomes', 'clentaminator'],
    mustHave: true,
    pylonTarget: '—',
    status: 'correct',
    emoji: '⚙️',
  },
  {
    id: 'cyborg',
    name: 'Cyborg',
    biome: 'Flexible',
    partner: '—',
    role: 'Objets high-tech / roquettes',
    priority: 20,
    notes: 'Arrive après Plantera. Vends des roquettes et de l\'équipement tech.',
    phase: 'hardmode',
    utility: ['armes', 'roquettes'],
    mustHave: false,
    pylonTarget: '—',
    status: 'correct',
    emoji: '🤖',
  },
  {
    id: 'dure-a-cuire',
    name: 'Duende à cuire',
    biome: 'Désert',
    partner: 'Marchand d\'armes',
    role: 'Armes de dégâts / stuff',
    priority: 17,
    notes: 'Arrive après le Hardmode. Aime le désert avec le Marchand d\'armes.',
    phase: 'hardmode',
    utility: ['armes', 'équipement'],
    mustHave: false,
    pylonTarget: 'Désert',
    status: 'correct',
    emoji: '💪',
  },
  {
    id: 'tax-collector',
    name: 'Percepteur',
    biome: 'Cavernes',
    partner: '—',
    role: 'Collecte de taxes',
    priority: 24,
    notes: 'PNJ spécial obtenu en lançant une potion de purification sur un Tortured Soul en enfer. Collecte l\'argent des autres PNJ.',
    phase: 'hardmode',
    utility: ['taxes'],
    mustHave: false,
    pylonTarget: 'Cavernes',
    status: 'correct',
    emoji: '🧾',
  },
  {
    id: 'princesse',
    name: 'Princesse',
    biome: 'Flexible',
    partner: '—',
    role: 'Objets royaux / déco',
    priority: 25,
    notes: 'Dernier PNJ. Apprécie tous les biomes. Idéale partout.',
    phase: 'hardmode',
    utility: ['déco', 'spécial'],
    mustHave: false,
    pylonTarget: '—',
    status: 'excellent',
    emoji: '👑',
  },
  {
    id: 'golfer',
    name: 'Golfeur',
    biome: 'Forêt',
    partner: 'Zoologiste',
    role: 'Objets de golf',
    priority: 18,
    notes: 'Trouvé dans le désert souterrain. Aime la forêt avec la Zoologiste.',
    phase: 'pre-hardmode',
    utility: ['golf', 'fun'],
    mustHave: false,
    pylonTarget: 'Forêt',
    status: 'correct',
    emoji: '🏌️',
  },
  {
    id: 'skeleton-merchant',
    name: 'Marchand squelette',
    biome: 'Cavernes',
    partner: '—',
    role: 'Objets rares souterrains',
    priority: 26,
    notes: 'PNJ itinérant des cavernes. Pas de logement permanent. Achats utiles en exploration.',
    phase: 'pre-hardmode',
    utility: ['shop', 'exploration'],
    mustHave: false,
    pylonTarget: '—',
    status: 'correct',
    emoji: '💀',
  },
]

export const VILLAGE_GROUPS: VillageGroup[] = [
  {
    biome: 'Forêt',
    npcs: ['Guide', 'Zoologiste'],
    pylon: 'Pylône de la Forêt',
    phase: 'pre-hardmode',
    priority: 4,
    description: 'Le duo de départ. Guide + Zoologiste s\'entendent bien. Ajoutez le Golfeur si besoin.',
    emoji: '🌲',
    color: '#2D5A3D',
  },
  {
    biome: 'Désert',
    npcs: ['Infirmière', 'Marchand d\'armes'],
    pylon: 'Pylône du Désert',
    phase: 'pre-hardmode',
    priority: 1,
    description: 'Le meilleur duo du jeu. Soins + armes. Pylône facile à obtenir. Prioritaire.',
    emoji: '🏜️',
    color: '#C8A951',
  },
  {
    biome: 'Jungle',
    npcs: ['Dryade', 'Sorcier vaudou'],
    pylon: 'Pylône de la Jungle',
    phase: 'pre-hardmode',
    priority: 3,
    description: 'Dryade + Sorcier vaudou. Buffs + invocation. Très bon duo.',
    emoji: '🌴',
    color: '#228B22',
  },
  {
    biome: 'Neige',
    npcs: ['Mécano', 'Gobelin bricoleur'],
    pylon: 'Pylône de la Neige',
    phase: 'pre-hardmode',
    priority: 2,
    description: 'Mécano + Gobelin. Wiring + reforge. Indispensable dès que possible.',
    emoji: '❄️',
    color: '#A8D8EA',
  },
  {
    biome: 'Océan',
    npcs: ['Marchand', 'Pêcheur'],
    pylon: 'Pylône de l\'Océan',
    phase: 'pre-hardmode',
    priority: 5,
    description: 'Marchand + Pêcheur. Duo correct pour pylône océan. Pas prioritaire.',
    emoji: '🌊',
    color: '#4A90D9',
  },
  {
    biome: 'Cavernes',
    npcs: ['Démolisseur', 'Tavernkeep'],
    pylon: 'Pylône des Cavernes',
    phase: 'hardmode',
    priority: 6,
    description: 'Démolisseur + Tavernkeep. Explosifs + sentinelles. Utile en milieu de partie.',
    emoji: '⛏️',
    color: '#8B4513',
  },
  {
    biome: 'Hallow',
    npcs: ['Party Girl', 'Magicien'],
    pylon: 'Pylône du Hallow',
    phase: 'hardmode',
    priority: 7,
    description: 'Party Girl + Magicien. Fête + magie. Duo hallow parfait.',
    emoji: '✨',
    color: '#FF69B4',
  },
  {
    biome: 'Champignon',
    npcs: ['Truffle', 'Flexible'],
    pylon: 'Pylône du Champignon',
    phase: 'hardmode',
    priority: 8,
    description: 'Truffle seul dans son biome. Ajoutez un PNJ flexible (Coiffeur, Peintre).',
    emoji: '🍄',
    color: '#9370DB',
  },
]

export const CONSTRUCTION_TIPS = [
  '🚫 Laissez plus de 25 blocs entre PNJ qui ne doivent PAS être voisins',
  '📏 Visez environ 120 blocs entre chaque mini-village',
  '🏘️ Évitez les grosses villes uniques — privilégiez des duos par biome',
  '🎯 Placez les PNJ importants dans leurs biomes préférés pour le bonheur max',
  '🏪 Pensez aux pylônes dès le début de partie',
  '🔧 La Mécano + Gobelin = duo reforge prioritaire pour économiser',
  '❤️ L\'Infirmière + Marchand d\'armes = meilleur duo pour pylône désert',
  '🧹 Vérifiez que le biome est bien celui attendu (mesure avec la musique/background)',
  '🏠 Maison valide = 60 blocs minimum, table+chaise, lumière, porte, mur de fond',
]

export const PHASE_ORDER = [
  { phase: 1, label: '🌲 Étape 1 — Désert', desc: 'Infirmière + Marchand d\'armes (pylône désert)' },
  { phase: 2, label: '❄️ Étape 2 — Neige', desc: 'Mécano + Gobelin bricoleur (pylône neige)' },
  { phase: 3, label: '🌴 Étape 3 — Jungle', desc: 'Dryade + Sorcier vaudou (pylône jungle)' },
  { phase: 4, label: '🌲 Étape 4 — Forêt', desc: 'Guide + Zoologiste (pylône forêt)' },
  { phase: 5, label: '🌊 Étape 5 — Océan', desc: 'Marchand + Pêcheur (pylône océan)' },
  { phase: 6, label: '⛏️ Étape 6 — Cavernes', desc: 'Démolisseur + Tavernkeep (pylône cavernes)' },
  { phase: 7, label: '✨ Étape 7 — Hallow', desc: 'Party Girl + Magicien (pylône hallow)' },
  { phase: 8, label: '🍄 Étape 8 — Champignon', desc: 'Truffle + Flexible (pylône champignon)' },
]

export const CHECKLIST_ITEMS = [
  { id: 'houses', label: '🏠 Maisons valides construites', category: 'construction' },
  { id: 'pylon', label: '📡 Pylône acheté', category: 'progression' },
  { id: 'distance', label: '📏 Distance correcte entre villages (120+ blocs)', category: 'placement' },
  { id: 'duo', label: '👥 Duo principal installé', category: 'placement' },
  { id: 'biome', label: '🌍 Biome vérifié (musique / fond)', category: 'verification' },
  { id: 'secure', label: '🛡️ Village sécurisé (murs, lumière)', category: 'construction' },
  { id: 'access', label: '🚪 Accès rapide pratique (téléportation, ponts)', category: 'quality' },
  { id: 'npc25', label: '📐 25+ blocs entre voisins non désirés', category: 'placement' },
]

export const BIOME_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  'Forêt': { bg: '#f0f7f0', text: '#2D5A3D', border: '#4a8c5c' },
  'Désert': { bg: '#faf5eb', text: '#8B7355', border: '#C8A951' },
  'Jungle': { bg: '#f0faf0', text: '#1a6b1a', border: '#228B22' },
  'Neige': { bg: '#f0f8ff', text: '#4a6fa5', border: '#A8D8EA' },
  'Océan': { bg: '#eef5fb', text: '#2a5a8a', border: '#4A90D9' },
  'Cavernes': { bg: '#f5f0eb', text: '#6b3a1a', border: '#8B4513' },
  'Hallow': { bg: '#fef0f7', text: '#c44a7a', border: '#FF69B4' },
  'Champignon': { bg: '#f8f0fc', text: '#6a3a8a', border: '#9370DB' },
  'Flexible': { bg: '#f5f5f5', text: '#555555', border: '#999999' },
}
